palladiumkenya/kenyaemr-esm-3.x

- .github/pull_request_template.md
- packages/esm-patient-flags-app/src/index.ts
- packages/esm-patient-flags-app/src/patient-flags/patient-flags.component.tsx
- packages/esm-patient-flags-app/src/patient-flags/patient-flags.scss
- Add pull_request_template for this module.
- Add `patient-flags-slot` to display patient flags.
- Add styles for patient-flags component
> Add patient-flags slot and add pr template

- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.test.tsx
- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
- Fixes a bug related to launching enrollment forms in edit or discontinuation mode.
- Adds a validation check to display an error message when an `encounterUuid` is missing during enrollment editing.
**Details**:
While addressing the issue with enrollment forms not launching correctly in edit or discontinuation mode, I noticed that there was no error handling for scenarios where the `encounterUuid` was missing during the editing of enrollments. To enhance the user experience and prevent potential errors, I've implemented a check to display an informative error message in such cases.
*None.*
*None.*
*None.*
> (fix) Fix: Correctly launch enrollment forms in edit or discontinuation mode

- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.test.tsx
- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.scss
This PR adds the overflow menu on enrollment component and `see more..` button to view all the records.
*None.*
*None.*
> (enhc) Add overflow menu for edit and delete buttons

- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
Add reason for discontinuation in HIV summary under completed tab. 
*None.*
*None.*
*None.*
> Add reason for discontinuation in HIV summary under completed tab.

- packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.component.tsx
- packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.scss
- packages/esm-billing-app/src/invoice/payments/payments.component.tsx
- packages/esm-billing-app/src/invoice/payments/payments.scss
This pull request updates the UI for invoice management. Key changes include:
1. Renaming the button for closing the invoice section to 'Discard' for clearer action indication.
2. Modifying the delete button to solely display the button element, streamlining its appearance.
3. Relocating the 'Process Payment' option to a fixed section. This ensures its position remains constant on the UI, irrespective of the number of payment methods added.
*None.*
*None.*
*None.*
> (feat) improve wording and layout

- packages/esm-billing-app/src/invoice/printable-invoice/printable-invoice.component.tsx
This PR fixes an error on print component to prevent `undefined` error on the empty array
*None.*
*None.*
*None.*
> (fix) rowData in print preview should default to empty array

- packages/esm-billing-app/src/bills-table/bills-table.scss
This PR restores a bottom border to the bill list data table's empty state that gets shown when the user filters the table content and there are no matching results to show.
*None.*
*None.*
> (fix) Fix bottom border for datatable filter empty state

- packages/esm-billing-app/src/invoice/invoice-table.component.tsx
- packages/esm-billing-app/src/invoice/invoice-table.scss
I've fixed the following issues in the line items datatable:
- Change the table description content to match the designs
- Apply some margin to the info tooltip icon 
> Before
> After
*None*
*None*
> (fix) Line items table header fixes

- packages/esm-billing-app/src/invoice/invoice.component.tsx
- packages/esm-billing-app/src/invoice/invoice.scss
I've made some adjustments to the bill printing workflow with the view of improving the user experience. These include:
- Not rendering the print preview component on the page.
- Disabling the print button when printing.
> Before
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8509731/24b323d7-8858-4b80-9d4f-cc67207f9751
> After
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8509731/853653e3-a6c9-484a-9f98-41e44e723108
*None.*
*None.*
> (feat) Improvements to bill printing

- packages/esm-billing-app/src/bill-history/bill-history.component.tsx
- packages/esm-billing-app/src/invoice/invoice-table.component.tsx
- packages/esm-billing-app/src/invoice/invoice-table.scss
I've removed the info tooltip that sat next to the line items table header description. This is following guidance from Ted. The designs will be updated appropriately in future.
*None.*
*None.*
> (feat) Remove info toolip from line items table header

- packages/esm-billing-app/src/bills-table/bills-table.component.tsx
- packages/esm-billing-app/src/bills-table/bills-table.scss
Fixes the placement of the background data fetching indicator in the bill list table header.
*None.*
*None.*
> (fix) Fix placement of background data fetching indicator

- packages/esm-patient-flags-app/jest.config.js
- packages/esm-patient-flags-app/src/clear-cache/clear-cache.component.test.tsx
- packages/esm-patient-flags-app/src/hooks/usePatientId.tsx
- packages/esm-patient-flags-app/src/kenyaemr-link/kenyaemr-chart-link.component.tsx
- packages/esm-patient-flags-app/src/kenyaemr-link/kenyaemr-chart-link.test.tsx
- packages/esm-patient-flags-app/src/patient-flags/patient-flags.component.tsx
- packages/esm-patient-flags-app/src/patient-flags/patient-flags.scss
- packages/esm-patient-flags-app/src/patient-flags/patient-flags.test.tsx
- packages/esm-patient-flags-app/src/root.component.tsx
This PR makes changes to `esm-patient-flags` to do the following.
1. Remove unused file `root.component.tsx`
2. Update test to a coverage of `80`% 
3. Update the flags colors to be similar to whats on 2.x and requested in the UAT. cc Keziah, @palladiumkenya/qa
4. Use `userEvent` and replace `fireEvent` in test to simulate user interactions
*None.*
*None.*
*None.*
> (feat) Update flags apperance and update unit test to `80`%

- packages/esm-patient-clinical-view-app/src/clinical-view-group/createDashboardGroup.tsx
- packages/esm-patient-clinical-view-app/src/clinical-view-group/dashboard-group.component.tsx
- packages/esm-patient-clinical-view-app/src/clinical-view-group/dashboard-group.scss
- packages/esm-patient-clinical-view-app/src/clinical-view-group/dashboard-group.test.tsx
- packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
- packages/esm-patient-clinical-view-app/src/index.ts
- packages/esm-patient-clinical-view-app/src/routes.json
This PR adds custom grouping for clinical views. I have also wired`MCH Dashboard` to the view.
``` json
{
"name": "mch-dashboard-link",
"component": "mchDashboardLink",
"slot": "patient-clinical-view-slot",
"order": 11,
"meta": {
"columns": 1,
"columnSpan": 1,
"slot": "patient-chart-mch-dashboard-slot",
"path": "mch-dashboard",
"layoutMode": "anchored"
}
}
```
The above code attaches the `mch-dashboard-linkl` to our custom slot. The dashboard to be displayed is defined her
``` json
{
"name": "mch-clinical-view",
"slot": "patient-chart-mch-dashboard-slot",
"component": "mchClinicalView",
"order": 0,
"online": true,
"offline": false
}
```
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/635f401a-49c2-4473-a108-422ead2a99ae
At the moment we need to define an expression to …
> (feat) Add patient-chart-clinical-views group link

- packages/esm-patient-flags-app/src/patient-flags/patient-flags.scss
Revert back to original color theme for  flags
*None.*
*None.*
*None.*
> (feat) revert to origal flags styling

- packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
- packages/esm-patient-flags-app/src/navbar/navbar-overlay.component.tsx
This PR adds `billable services` link to custom navbar, which is shown when user has admin level privileges.
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/d58cdb83-644f-423b-b66a-c357ee5f6880
*None.*
*None.*
> (feat) Add billable service link on nav menu.

- jest.config.js
- packages/esm-care-panel-app/src/patient-summary/patient-summary.component.test.tsx
- packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx
- packages/esm-care-panel-app/src/program-summary/program-summary.test.tsx
- packages/esm-patient-clinical-view-app/src/data-table/o-table.component.test.tsx
- packages/esm-patient-clinical-view-app/src/encounter-list/encounter-list.component.test.tsx
This PR adds a global testTimeout property to the Jest configuration so that tests know to run within a 15000ms timeout. This should hopefully fix issues with tests timing out non-deterministically.
*None*
*None*
*None*
> (test) Add global test timeout to Jest config

- packages/esm-care-panel-app/src/hooks/usePatientSummary.ts
- packages/esm-care-panel-app/src/patient-summary/patient-summary.component.test.tsx
- packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx
This PR fixes an issue with the care panel summary component where the component would fail to render owing to an issue with the date format of the `cd4CountDate` property in the API response. Specifically, this field is a `Date` with the format `DD/MM/YYYY` (which is different than the ISO strings we get back for other date fields). 
The logic that handles rendering the field in the UI invokes the `new Date` constructor on the `cd4CountDate` which would fail silently:
I've added special handling for dates of this format so that the date conversion using `formatDate` and the `new Date` constructor doesn't fail, causing the whole component to fail to render.
> Before
> After
*None*
*None*
*None*
> (fix) Fix date rendering in care panel summary

- packages/esm-billing-app/src/bill-history/bill-history.component.tsx
- packages/esm-billing-app/src/billing-form/billing-form.component.tsx
- packages/esm-billing-app/src/bills-table/bills-table.test.tsx
- packages/esm-billing-app/src/invoice/payments/utils.ts
- packages/esm-billing-app/translations/en.json
This PR adds previous payment to process payment endpoint. This is to avoid losing previous payment information.
The side effect is that line-items aren't returned by bills endpoint. @jecihjoy do you have an idea why?
Also include a `launch` button for `Billing form` on patient chart
*None.*
*None.*
*None.*
> (fix) Add previous payment details to process payment endpoint

- package.json
- packages/esm-patient-clinical-view-app/src/clinical-encounter/summary/out-patient-summary/patient-medical-history.component.tsx
- packages/esm-patient-clinical-view-app/src/clinical-encounter/summary/out-patient-summary/patient-social-history.component.tsx
- packages/esm-patient-clinical-view-app/src/hooks/useClinicalEncounter.ts
- packages/esm-patient-clinical-view-app/src/special-clinics/hiv-care-and-treatment-services/defaulter-tracing/defaulter-tracing.component.tsx
- yarn.lock
Revamed clinical encounter views to use a table instead of summary cards to avoid repeated column headers.
Changed defaulter tracing view from expandable table to classic table.
*None.*
*None.*
> (enhc) further improvements on outpatient clinical views

- packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
- packages/esm-billing-app/src/routes.json
This PR adapts billing check in form to use `extra-visit-attribute-slot` relating to the merged [PR](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1700) 
*None.*
*None.*
*None.*
> (feat) Adapt billing checkin form to use extra-visit attribute slot

- packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
- packages/esm-billing-app/src/billing-form/billing-form.resource.tsx
- packages/esm-billing-app/translations/en.json
Create a Search function instead of the dropdown function in billable services in the check-in Form
Create a Search function instead of the dropdown function in billable services in the check -in Form
Image Before when it was using a dropdown function
image when the search function was implemented
*None.*
*None.*
*None.*
> (feat) create search function instead of the dropdown function in billable services in the check-in form

- packages/esm-billing-app/package.json
- packages/esm-billing-app/src/index.ts
Attempting to address an issue where the clinical forms fail due to billing @openmrs/esm-patient-common-lib. This PR serves as a last-ditch effort to resolve potential conflicts arising from shared peer dependencies.
*None.*
*None.*
*None.*
> (chore) attempt to resolve failing workspace by forcing billing to have own version of common lib

- packages/esm-claims-app/src/dashboard.meta.ts
- packages/esm-claims-app/src/index.ts
- packages/esm-claims-app/src/routes.json
- packages/esm-version-app/src/release-version.js
Fix issue with Claims dashboard menu not showing
*None.*
*None.*
> Khp3 5393 claims management

- packages/esm-morgue-app/package.json
- yarn.lock
Moving `@openmrs/esm-patient-common-lib` to peer dependency since having it as a dependency bundles it in the generate dist and results in error at run time as there are multiple versions of the same dependency. cc @ojwanganto this resolves the error you are seeing while launching the workspace. Thanks
*None.*
*None.*
*None.*
> (fix) fix share `@openmrs/esm-patient-common-lib` leading to run time error

- packages/esm-billing-app/src/billable-services/billiable-item/drug-order.component.tsx
- packages/esm-billing-app/src/billable-services/billiable-item/drug-order.scss
- packages/esm-billing-app/src/billable-services/billiable-item/lab-order.component.tsx
- packages/esm-billing-app/src/billable-services/billiable-item/useBilliableItem.tsx
- packages/esm-billing-app/src/index.ts
- packages/esm-billing-app/src/routes.json
- packages/esm-billing-app/src/types/index.ts
- packages/esm-billing-app/translations/en.json
- packages/esm-morgue-app/package.json
- yarn.lock
see 👉🏽  https://openmrs.atlassian.net/browse/O3-3128
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/bfb391e7-920d-406b-9205-983b71a0a39a
https://github.com/openmrs/openmrs-esm-patient-chart/pull/1818
@ojwanganto @patryllus  we will need to update the stock inventory endpoint to allow clinical staff access stock levels. 
*None.*
> O3-3128: Add ability to show lab and drug order prices and stock levels

- package.json
- packages/esm-billing-app/package.json
- packages/esm-care-panel-app/package.json
- packages/esm-claims-app/package.json
- packages/esm-morgue-app/package.json
- packages/esm-patient-clinical-view-app/package.json
- packages/esm-shr-app/package.json
- yarn.lock
Align `@openmrs/esm-patient-common-lib` package to squash error on launching workspaces.
*None.*
*None.*
*None.*
> (fix) Align `@openmrs/esm-patient-common-lib` to use one version provided by patient-chart

- packages/esm-billing-app/src/bills-table/bills-table.component.tsx
This PR adds `POSTED` bills status for bills that have partial payments which are considered pending indicating no payments have been made for that particular bill
*None.*
*None.*
*None.*
> (feat) Add filter to show posted bills

- packages/esm-billing-app/src/bill-history/bill-history.component.tsx
- packages/esm-billing-app/src/bill-history/bill-history.test.tsx
- packages/esm-billing-app/translations/en.json
- yarn.lock
see https://thepalladiumgroup.atlassian.net/browse/KHP3-5867
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/e5f1ae79-b0de-42fc-ae24-e565cfec0fdd
*None.*
*None.*
> (feat) KHP3-5867 : Add restriction to require an active visit before launching billing form

- packages/esm-billing-app/src/invoice/payments/payments.component.tsx
Change total amount to reflect correctly in the invoice breakdown Change client balance/total amount due to show correct balance on posted bills
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/35590825/9c85e711-f7cf-474d-99fd-0ca142231583
*None.*
*None.*
> (fix) : fix error on picking the correct bill total amount

- packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx
- packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.resource.tsx
The root cause of this is moving from `@openmrs` to `@kenyaemr` module for queue management. This resulted in the `usePatientQueues` to fail silently.  In addition to this fix, i have also disable picking up lab order if fulfiller status is `IN_PROGRESS`
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/b8a14a2e-9dd2-45f1-bf7a-579443e7ed41
https://github.com/palladiumkenya/openmrs-config-kenyaemr/pull/643
*None.*
> (fix) fix showing picking lab order action button

- e2e/core/location-selector.ts
- e2e/core/test.ts
- e2e/pages/billing-page.ts
- e2e/pages/home-page.ts
- e2e/pages/index.ts
- e2e/specs/billing/billling-history.spec.ts
- e2e/specs/login-test.spec.ts
Since I started working on this project I have noticed a recurring failing tests in most pull requests. I investigated the cause of issue was that the tests did not account for when playwright is redirected to the **select login location page**. In this PR I have fixed the issue by adding a global event listener that listens when the page changes to the aforementioned one and automatically selects the first login location and logs inthe test client.
This playwright client kept failing with errors such as 
```
Error: Timed out 40000ms waiting for expect(received).toHaveURL(expected)
Expected string: "https://dev.kenyahmis.org/openmrs/spa/home"
Received string: "https://dev.kenyahmis.org/openmrs/spa/login/location"
```
The reason why the playwright client timed out is because it was looking …
> Fix (tests) broken 'e2e' tests.

- e2e/specs/billing/billling-history.spec.ts
Yesterday evening I opened this PR #284 . Yeah whilst I thought I had addressed all the issues I was surprised to still notice failing e2e tests this morning. This prompted an investigation and I found out an edge case that I and the person who had originally written the test had overlooked. The tests for accessing and manipulating the billing table only passed If the bills table existed. Since those elements are conditionally rendered on the app if there are no bills the tests fail.
Funny enough thats why my tests passed yesterday since playwright runs against the dev environment which there is almost a 100% certainty there will be bills in the evenings haha.
In this PR I have updated the tests to check for the availability of the rendered bills table and thereby proceed with the tests …
> fix (tests) : broken e2e tests to handle no bills cases

- packages/esm-patient-clinical-view-app/src/case-management/table/case-management-list-active-component.tsx
- packages/esm-patient-clinical-view-app/src/case-management/table/case-management-list-inactive-component.tsx
- packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
- packages/esm-patient-clinical-view-app/src/routes.json
see: https://thepalladiumgroup.atlassian.net/browse/KHP3-6250
*None.*
*None.*
*None.*
> KHP3-6250: Patient Selection Should Redirect to Case Management on the Patient Chart Instead of Home

- packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
- packages/esm-pharmacy-app/src/pharmacy-tables/pharmacy-patients.component.tsx
- packages/esm-pharmacy-app/translations/en.json
Cleaned up community pharmacy
Linked Pharmacy patient to Patient chart upon click
*None.*
*None.*
> Added link to pharmacy patient, cleaned up community pharmacy

- packages/esm-lab-manifest-app/src/config-schema.ts
- packages/esm-lab-manifest-app/src/forms/lab-manifest-form.scss
- packages/esm-lab-manifest-app/src/forms/lab-manifest-form.workspace.tsx
- packages/esm-lab-manifest-app/src/forms/lab-manifest-orders-to-manifest.modal.tsx
- packages/esm-lab-manifest-app/src/forms/sample-delete-confirm-dialog.modal.tsx
- packages/esm-lab-manifest-app/src/hooks/useActiveRequests.ts
- packages/esm-lab-manifest-app/src/index.ts
- packages/esm-lab-manifest-app/src/lab-manifest.resources.ts
- packages/esm-lab-manifest-app/src/routes.json
- packages/esm-lab-manifest-app/src/tables/lab-manifest-active-requests.component.tsx
- packages/esm-lab-manifest-app/src/tables/lab-manifest-samples.component.tsx
- packages/esm-lab-manifest-app/src/types/index.ts
https://thepalladiumgroup.atlassian.net/browse/KHP3-6301
- Made valid orders table selectable
- Implemented modal dialog form for prompting addition sample information
- Removing sample from the manifest
*None.*
*None.*
> Khp3 6301 add ability to add multiple orders to the lab manifest

- packages/esm-billing-app/src/billable-services/billable-services.component.tsx
- packages/esm-billing-app/src/billable-services/create-edit/update-billable-service.component.tsx
- packages/esm-billing-app/src/billable-services/create-edit/update-billable-services.scss
- packages/esm-billing-app/src/index.ts
- packages/esm-billing-app/src/routes.json
https://github.com/user-attachments/assets/1f8bf417-3da0-44fa-a872-ecd53d4cb000
*None.*
*None.*
*None.*
> Update billable services workspace

- packages/esm-billing-app/src/bill-history/bill-history.component.tsx
- packages/esm-billing-app/src/bill-history/bill-history.scss
- packages/esm-billing-app/src/bill-history/bill-history.test.tsx
- packages/esm-billing-app/translations/en.json
…state
see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6329
*None.*
*None.*
*None.*
> KHP3-6329: Restore Card Header Layout in Billing History Table

- packages/esm-patient-clinical-view-app/src/clinical-encounter/dashboard/clinical-encounter-dashboard.component.tsx
In this PR I have fixed a small css issue that caused the height of the clinical encounters dashboard to be broken. The issue was a on the community that targetted all extension children and set their height to 100% see [here.](https://github.com/openmrs/openmrs-esm-patient-chart/blob/1d1e39cb2aaff7666bdcd8d83dcf96f64f2cf74b/packages/esm-patient-chart-app/src/patient-chart/chart-review/dashboard-view.scss#L30)
cc @donaldkibet .
*None.*
*None.*
*None.*
> (fix) : Clinical encounter UI height issue.

- packages/esm-billing-app/src/billable-services/billable-services-home.component.tsx
- packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
- packages/esm-billing-app/src/billable-services/manage-commodity-price/manage-commodity-price.component.tsx
- packages/esm-billing-app/translations/en.json
The added item enables privileged users to access a component through which they can edit the prices of non-pharm commodities. As it is, these commodities are billed at the buying price.
*None.*
*None.*
*None.*
> (feat): add sidenav item linking to managecommodityprices component

- packages/esm-shr-app/src/config-schema.ts
- packages/esm-shr-app/src/constants.ts
- packages/esm-shr-app/src/hooks/usePatientIdentifiers.ts
- packages/esm-shr-app/src/shr-summary/shr-authorization-form.workspace.tsx
- packages/esm-shr-app/src/shr-summary/shr-forms.scss
- packages/esm-shr-app/src/shr-summary/shr-summary.component.tsx
- packages/esm-shr-app/src/shr-summary/shr-summary.resource.ts
- Cleaned SHR Summary Pannel Code
- Requireing SHA Number before pulling SHR Summary in place of Initial NUPI
https://thepalladiumgroup.atlassian.net/browse/KHP3-6494
*None.*
> KHP3-6494-add-sha-number-requirement-before-pulling-shr-summary-data

- packages/esm-billing-app/src/hooks/useRequestStatus.tsx
- packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
- packages/esm-billing-app/src/utils.ts
This PR adds a UI fix to auto close the payment dialog after successfull mpesa payment.
https://github.com/user-attachments/assets/4b0c6a56-071d-4512-908f-f4f2ad40708c
*None.*
*None.*
cc @ojwanganto
> feat: close mpesa dialog on successful mpesa payment completion

- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-form.test.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-form.workspace.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-util.ts
This fix ensures that the user does not manually edit the price on the textbox. However, the user will be able to select price from the available service prices attached to the billable item.
[editbill.webm](https://github.com/user-attachments/assets/f61505f9-b092-4db3-8e4c-b31abe4dd7c3)
*None.*
*None.*
*None.*
> (fix) Restricted manual editing of price when Editing Bill Line Item

- packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
- packages/esm-patient-clinical-view-app/src/clinical-view-group/clinical-view-group.resource.ts
- packages/esm-patient-clinical-view-app/src/clinical-view-group/createDashboardGroup.tsx
This PR adds ability to show clinical nav group once a user has been discontinued from the care program
Follow up PR to ensure the dashboard link is update with every update
*None.*
*None.*
*None.*
> (fix) : Fix issue with display special clinic data once user is discontinued from the program

- packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/utils.tsx
When starting regimen we now calculate age of the patient as when the regimen was started. This depends on the visit date/Regimen start date the user selected. If the regimen was started when you are a child, child regimen lines will be shown. 
See the different regimen line for same patient based on the date selected
*None.*
*None.*
> (fix): Show regimeline based on patient age when regimen was started 

- packages/esm-billing-app/src/billable-services/billables/services/service-form.workspace.tsx
- packages/esm-billing-app/src/billable-services/dashboard/dashboard.component.tsx
This PR fixes an issue with forms on billing app not working correctly because of having multiple workspace context provided for the same workspace. 
https://github.com/user-attachments/assets/9ec90cc7-a6c0-45f1-a847-bfbaa90127d3
*None.*
*None.*
> (fix) : fix: resolve service status toggle button issue caused by multiple workspace contexts

- packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx
Converted overflowmenuitem to Button for slot consumption
*None.*
*None.*
> (Fix) Converted overflowmenuitem to Button for slot consumption

- packages/esm-billing-app/src/billing-prompt/billing-prompt.resource.tsx
- packages/esm-billing-app/src/billing.resource.ts
- packages/esm-billing-app/src/config-schema.ts
- packages/esm-billing-app/src/modal/require-payment.resource.tsx
This PR ensures that the prompt always evaluates the patient bills to ensure that past bills which haven't been settled are evaluated when determining whether to show the billing prompt. Previous version only evaluated bills on the current date time
*None.*
*None.*
*None.*
> (fix) : fix billing prompt by logic for retrieving patient bill

- packages/esm-billing-app/src/billable-services/billables/charge-summary-table.component.tsx
- packages/esm-billing-app/src/billable-services/billables/commodity/commodity-form.workspace.tsx
- packages/esm-billing-app/src/billable-services/billables/form-helper.ts
- packages/esm-billing-app/src/billable-services/billables/services/service-form.workspace.tsx
- packages/esm-billing-app/src/billable-services/bulk-import-billable-service.modal.tsx
- packages/esm-billing-app/src/types/index.ts
- packages/esm-billing-app/translations/en.json
This PR handles 3 main things
1. Add error handling in the event the payload isn't constructed correctly, this happens because charge item may have been created with the wrong concept id. In this event @ojwanganto we might want to provide ability to validate the bulk import to ascertain that charge items created using this method have valid concept uuids.
2. Moved the bulk import functionality under the `Actions` combo box to centralized functionality on the summary table.
3. Add ability to download `template excel` file to be used for bulk upload. 
https://github.com/user-attachments/assets/b8fac0dc-f598-4668-8773-386020b0f3a4
*None.*
*None.*
> (fix) : handle error on creating charge items payload and adjust bulk upload button

- packages/esm-billing-app/src/payment-points/payment-point/clock-in.component.tsx
This PR fixes a small early return issue when no payment points are provided to the clock-in component. Fixes an issue where the component would crash with undefined on the payment point name.
*None.*
*None.*
*None.*
> fix: correctly early return when no payment point is provided

- packages/esm-care-panel-app/src/regimen-editor/utils.tsx
The TB regimen line were being filtered out hence no way one would be able to select the regimen. The fix here is to ensure that TB regimen lines are getting included and still take into account the age factor.
*None.*
*None.*
*None.*
> (fix) KHP-6723: Enable regimen initiation for TB clients

- packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx
- packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.test.tsx
- packages/esm-billing-app/src/index.ts
To integrate billing with various order modules (Imaging, Procedures, and Drugs). This (PR) enhances the bill payment status action button to accommodate different needs:
When users click "Pick Order," the system should be able to launch module-specific modals for:
1. Lab tests
2. Procedures
3. Drugs
4. Imaging(i.e Radiology)
No UI changes
*None.*
*None.*
> (feat) KHP3-6909: Expand test order slot to allow passing of additional props

- packages/esm-providers-app/src/constants.ts
- packages/esm-providers-app/src/table/provider-data-table.resource.ts
- packages/esm-providers-app/src/workspace/hook/provider-form.resource.ts
- packages/esm-providers-app/src/workspace/provider-form.scss
- packages/esm-providers-app/src/workspace/provider-form.workspace.tsx
Fixed:
- Gender field not picking current provider gender when performing update due to the field not being included in provider custom representation
- Auto logout when invalid HWR Credentials are used or are not configured (No not logging out rather showing appropriate error message)
- Default identifier type not autofilling due to identifier search by display for a uuid value and also identifier types loading state not handled
https://github.com/user-attachments/assets/dc7556cf-66ff-4c44-9d9c-286c726dbfbd
*None.*
https://thepalladiumgroup.atlassian.net/browse/KHP3-6911
https://thepalladiumgroup.atlassian.net/browse/KHP3-6912
https://thepalladiumgroup.atlassian.net/browse/KHP3-6913
*None.*
> (fix) KHP3-6911: Fix provider app bugs - gender field, HWR credentials, and identifier type issues

- packages/esm-billing-app/src/billing-form/hie.resource.tsx
- packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.component.tsx
- packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.scss
- packages/esm-billing-app/src/config-schema.ts
This PR replaces the deprecated NUPI with SHA number. Also, its WIP to correctly get the HIE subscriptions from the backend.
*None.*
*None.*
*None.*
> (fix) : replace NUPI with SHA number

- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill-form.test.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill-form.workspace.tsx
- packages/esm-billing-app/src/utils.ts
- packages/esm-morgue-app/translations/en.json
This PR implements the initial functionality to capture and track reasons when waiving a bill. This is part of a larger feature set to enhance bill waiver management.
- Adds core infrastructure for bill waiver reason tracking
To complete this feature, the following items need to be implemented:
1. Default Waiver Payment Attribute
- Add functionality to capture waiver reasons during initialization
- Implement following community precedent (reference: [OpenMRS Reference Application](https://github.com/alaboso/openmrs-distro-referenceapplication/blob/660efc67c4f2b00e3e08b40f81952377091b28d8/distro/configuration/paymentmodes/paymentModes.csv))
2. Payment Method Enhancement
- Extend payment method functionality to handle all related properties and attributes
- Implement full CRUD operations …
> (feat) KHP3-6945 : Add ability to capture reason for waiving bills

- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-form.workspace.tsx
- packages/esm-billing-app/src/constants.ts
- packages/esm-billing-app/src/metrics-cards/metrics-cards.component.tsx
- packages/esm-billing-app/src/payment-modes/payment-attributes/payment-mode-attributes.component.tsx
- packages/esm-billing-app/src/payment-modes/payment-attributes/payment-mode-attributes.scss
- packages/esm-billing-app/src/payment-modes/payment-mode-dashboard.compont.tsx
- packages/esm-billing-app/src/payment-modes/payment-mode-dashboard.scss
- packages/esm-billing-app/src/payment-modes/payment-mode.workspace.test.tsx
- packages/esm-billing-app/src/payment-modes/payment-mode.workspace.tsx
- packages/esm-billing-app/src/payment-modes/usePaymentModeFormSchema.tsx
- packages/esm-billing-app/src/types/index.ts
This is the second part to having payment attributes work correctly. Its a follow up PR to [KHP3-6945](https://github.com/palladiumkenya/kenyaemr-esm-3.x/pull/426). This PR adds ability to define edit and delete payment attributes. We should be able to add reference to any payment made when the reference is available.
*None.*
*None.*
[KHP3-6945]: https://thepalladiumgroup.atlassian.net/browse/KHP3-6945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (feat) KHP3-6963 : Add ability to add and edit full payment mode attributes

- packages/esm-billing-app/src/claims/claims-wrap/claims-main.scss
- packages/esm-billing-app/src/claims/dashboard/form/claims-form.scss
- packages/esm-billing-app/src/claims/dashboard/table/claims-table.component.tsx
- packages/esm-billing-app/src/claims/dashboard/table/claims-table.scss
- packages/esm-billing-app/src/claims/metrics/metrics-card.scss
- packages/esm-billing-app/src/claims/metrics/metrics.scss
This PR fixes a simple layout issue to provide consistent padding and alignment on the patient claim page. Just a UX fix nothing major.
*None.*
*None.*
> (refactor) :   Standardize padding in patient claims page

- packages/esm-billing-app/src/claims/claims-management/table/claims-list-table.component.tsx
- packages/esm-billing-app/src/claims/claims-management/table/claims-list-table.scss
- packages/esm-billing-app/src/claims/claims-management/table/retry-claim-request.modal.tsx
- packages/esm-billing-app/src/claims/claims-management/table/use-facility-claims.ts
- packages/esm-billing-app/src/claims/dashboard/form/claims-form.resource.ts
- packages/esm-billing-app/src/index.ts
- packages/esm-billing-app/src/routes.json
- packages/esm-billing-app/src/types/index.ts
This PR makes changes that @donaldkibet requested on #422 and adds a new feature to retry failed claim requests by the client.
*None.*
*None.*
> (feat) : Add retry mechanism for failed claim requests

- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill/waive-bill-form.scss
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill/waive-bill-form.test.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill/waive-bill-form.workspace.tsx
- packages/esm-billing-app/src/billing.resource.ts
- packages/esm-billing-app/src/payment-modes/payment-mode-dashboard.compont.tsx
- packages/esm-billing-app/src/utils.ts
This PR introduces two key improvements to the waiver system:
1. Improved Error Handling
- Added validation for waiver reason payment attribute configuration
- Displays clear error message to administrators when the attribute is missing
2. Multiple Waiver Support
- Implemented ability to apply multiple waivers to a single bill
- Resolves limitation reported at Kayole where only one waiver could be applied
[Kapture 2024-11-07 at 09.31.53.webm](https://github.com/user-attachments/assets/7356e367-47e6-4d06-984e-0022f49b60df)
*None.*
*None.*
*None.*
> (feat) KHP3-6945 : Enhance waiving to support multiple waivers

- packages/esm-billing-app/src/config-schema.ts
- packages/esm-billing-app/src/hooks/useRequestStatus.tsx
- packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
- packages/esm-billing-app/src/m-pesa/mpesa-resource.tsx
- packages/esm-billing-app/src/types/index.ts
This PR adds a way to make STK push requests using the PDSL endpoint instead of the payment aggregator for facilities that opt to do so. I have tested to make sure our implementation did not break. I have also tested their endpoint and everything seems fine.
*None.*
*None.*
*None.*
> (feat): make pdsl stk push integration

- packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/regimen-reason.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
- packages/esm-care-panel-app/src/regimen-editor/standard-regimen.scss
[Screencast from 11-11-2024 05:20:42 ALASIRI.webm](https://github.com/user-attachments/assets/97532874-1110-492b-939a-71f2b3a66d66)
*None.*
*None.*
> (feat) KHP3-7059 : Add validation for regimen form

- packages/esm-billing-app/src/payment-points/payment-point/clock-in.component.tsx
This PR fixes the clock-in bug that the clock-in modal did not close even on success. The gist is I wasn`t checking for undefined on the payment point.
*None.*
*None.*
*None.*
> (fix) : prevent undefined errors by using correct payment endpoint

- packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx
Fix: Restore correct label text for pick-procedure component that was accidentally replaced with 'dispense' in PR #456
*None.*
*None.*
> (fix) : fix regression on `pick-procedure` action button

- packages/esm-billing-app/src/billable-services/bill-manager/bill-manager.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/cancel-bill/cancel-bill.workspace.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill/edit-bill-form.workspace.tsx
Previously, bill managers were unable to edit, delete, or waive bills that were older than 24 hours, limiting their ability to handle historical billing issues. This restriction has been removed to enable full bill management capabilities regardless of bill age.
- Added mutations for respective actions on delete/edit/cancel actions
[Kapture 2024-11-15 at 00.24.58.webm](https://github.com/user-attachments/assets/5e529405-2922-44cd-a9e3-1fdb36b069cb)
*None.*
*None.*
> (fix) : allow bill manager to modify bills beyond 24-hour limit

- __mocks__/bills.mock.ts
- packages/esm-billing-app/src/hooks/useRequestStatus.tsx
- packages/esm-billing-app/src/invoice/payments/payments.component.tsx
- packages/esm-billing-app/src/invoice/payments/payments.test.tsx
- packages/esm-billing-app/src/invoice/payments/utils.ts
This PR adds a way to settle a bill at the correct cash point. Previously it was assumed that where you create the bill is where it's settled.
*None.*
*None.*
*None.*
> fix: settle bills on correct cash point

- packages/esm-billing-app/src/prompt-payment/prompt-payment.resource.tsx
This PR adds a simple check to avoid firing a patient search call when a patient has not been searched. i.e the `patientUUID` is `undefined`.
*None.*
*None.*
*None.*
> (fix): disable fetch call when patient is undefined

- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.test.tsx
- packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
- packages/esm-care-panel-app/src/regimen/regimen-history.component.tsx
> (fix) Program enrollment && regimen history not loading

- packages/esm-billing-app/src/billable-services/billables/commodity/commodity-form.workspace.tsx
- packages/esm-billing-app/src/billable-services/billables/form-helper.ts
- packages/esm-billing-app/src/billable-services/billables/services/service-form.workspace.tsx
- packages/esm-patient-clinical-view-app/package-lock.json
This PR is linked to this (ticket)[https://thepalladiumgroup.atlassian.net/browse/KHP3-7113]. The issue had already been fixed. cc @ojwanganto @makombe @patryllus we might want to validate concepts while doing bulk update, this is to ensure that chargeable items are always associated with a charge item.
In this update, I have added a warning when we have incomplete data, so users are able to point out why enabling and disabling a service or stock item isn't working.
[Kapture 2024-11-28 at 16.06.12.webm](https://github.com/user-attachments/assets/e8777b21-986b-43be-a238-4b947c325582)
*None.*
*None.*
> (feat) KHP3-7113 : Deactivating a Billable item not working

- packages/esm-lab-manifest-app/src/config-schema.ts
- packages/esm-lab-manifest-app/src/forms/lab-manifest-form.scss
- packages/esm-lab-manifest-app/src/forms/lab-manifest-form.workspace.tsx
- packages/esm-lab-manifest-app/src/forms/lab-manifest-orders-to-manifest.modal.tsx
- packages/esm-lab-manifest-app/src/forms/sample-delete-confirm-dialog.modal.tsx
- packages/esm-lab-manifest-app/src/hooks/useIsKDoDSite.ts
- packages/esm-lab-manifest-app/src/hooks/usePatient.ts
- packages/esm-lab-manifest-app/src/tables/lab-manifest-samples.component.tsx
- packages/esm-lab-manifest-app/src/tables/patient-ccc-no-cell.component.tsx
- packages/esm-lab-manifest-app/src/tables/patient-name-cell.component.tsx
- Added patient name and ccc to to manifest sample for easy verification
- Added flu sample types
https://github.com/user-attachments/assets/4a21b945-8f2c-4e64-b882-8e0605456932
*None.*
*None.*
*None.*
> Add ccc and patient name to manifest samples table and flu sample types

- packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
- packages/esm-billing-app/src/billable-services/billables/charge-summary-table.component.tsx
- packages/esm-billing-app/src/billable-services/billables/form-helper.ts
- packages/esm-billing-app/src/billable-services/bulk-import-billable-service.modal.tsx
- packages/esm-billing-app/src/types/index.ts
This PR introduces a fix to solve the issue raised by QA whereby all bulk uploaded charge items were always set to **Stock Items** regardless of the service type ID provided. The fix was to use the service type UUID instead of the ID to pick the service type correctly.
*None.*
*None.*
*None.*
> (fix): use service type uuid and handle bulk upload payload construction errors

- packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/cancel-line-item.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/delete-bill-action-button.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/edit-line-item.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/refund-line-item.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/waive-bill-action-button.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/bill-line-items.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/bill-manager.component.tsx
- packages/esm-billing-app/src/billable-services/bill-manager/modals/refund-bill.modal.tsx
- packages/esm-billing-app/src/past-patient-bills/patient-bills.component.tsx
- Add ability to view refund action to only paid bills
- Add disable ability to edit/cancel paid bills
- View display full item name on bill manager search and patient search 
- Fix ability to display bill details for paid bills on  the bill manager search
https://github.com/user-attachments/assets/9a460370-cc95-4edf-a208-6668ad4b3e54
https://thepalladiumgroup.atlassian.net/browse/KHP3-7202
*None.*
> KHP3-7202   - Fix bugs on bill manager

- .gitignore
- packages/esm-billing-app/src/billable-services/payment-history/payment-history-table.component.tsx
- packages/esm-billing-app/src/config-schema.ts
- packages/esm-billing-app/src/helpers/functions.ts
- packages/esm-billing-app/src/prompt-payment/prompt-payment-modal.component.tsx
- packages/esm-billing-app/src/prompt-payment/prompt-payment.modal.test.tsx
- packages/esm-billing-app/src/prompt-payment/prompt-payment.resource.tsx
- packages/esm-billing-app/src/types/index.ts
ticket 👉🏽 https://thepalladiumgroup.atlassian.net/browse/KHP3-7230
Implements configurable payment enforcement periods for clinical services. Services like labs, medications, and imaging require payment before delivery, except for admitted patients.
Key changes:
- Payment enforcement based on configurable duration since last bill
- Payment prompt shows during enforcement period, hides after expiration
- Automatic bypass for admitted patients (in-patient)
Example: With 24-hour enforcement period, system displays payment prompt for 24 hours after bill creation, then hides prompt
[Kapture 2024-12-16 at 15.13.26.webm](https://github.com/user-attachments/assets/1d7b4577-48ee-4d88-bfa8-90edd4bcddb0)
*None.*
*None.*
> (feat) KHP3-7230 : Implement configurable payment based access control for clinical services

- package.json
- packages/esm-admin-app/package.json
- packages/esm-billing-app/package.json
- packages/esm-care-panel-app/package.json
- packages/esm-lab-manifest-app/package.json
- packages/esm-morgue-app/package.json
- packages/esm-patient-clinical-view-app/package.json
- packages/esm-patient-flags-app/package.json
- packages/esm-pharmacy-app/package.json
- packages/esm-providers-app/package.json
- packages/esm-shr-app/package.json
- packages/esm-version-app/package.json
Update to v5.3.8
*None.*
*None.*
*None.*
> (release) : v5.3.8

- packages/esm-billing-app/src/billing-dashboard/clock-out-strip.component.tsx
This a minimal fix turns out `${dayjs(globalActiveSheet.clockIn).format('D MMM YYYY, HH:MM A')}` gives you the top of the hour while `${dayjs(globalActiveSheet.clockIn).format('D MMM YYYY, HH:mm A')}` gives you the exact minute. So what would happen is you'd see **9:01 AM** instead of **9:22 AM**.
*None.*
*None.*
*None.*
> fix: changed MM to mm in clock in time display

- packages/esm-admin-app/src/components/users/manage-users/user-management.workspace.scss
- packages/esm-admin-app/src/components/users/manage-users/user-management.workspace.tsx
- packages/esm-admin-app/src/components/users/userManagementFormSchema.tsx
- packages/esm-admin-app/src/config-schema.ts
- packages/esm-admin-app/src/routes.json
- packages/esm-admin-app/src/user-management.resources.ts
- packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
* Create a provider
* Adds user Attributes 
- License number
- License expiry date
-Primary Facility
* Refactor user management Workspace
[Screencast from 08-01-2025 07:14:18 ALASIRI.webm](https://github.com/user-attachments/assets/bcbf3ed2-e001-44c5-97b2-ad6d884ecc83)
*None.*
*None.*
*None.*
> (feat) Create provider account

- packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
- packages/esm-billing-app/src/claims/metrics/metrics.component.tsx
- packages/esm-billing-app/translations/en.json
Renamed two labels in the form
Date of Claimed->Date of Claim
Diagnosis-> Final Diagnosis 
*None.*
*None.*
*None.*
> (Fix) renamed labels in claims form

- packages/esm-billing-app/src/billing-form/hie.resource.tsx
- packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.component.tsx
- packages/esm-billing-app/src/invoice/invoice.component.tsx
- packages/esm-billing-app/src/invoice/invoice.resource.ts
This PR
- Disables the claims button if the bill is not paid
- Removes the end visit confirmation modal
- Refactors the check on SHA before a user is billed on the visit form
*None.*
*None.*
Currently, the API for getting SHA returns a 202 successful response but the data is inaccurate. I do not think that should stand in the way of this PR getting merged because when the backend guys fix that everything will be smooth sailing.
> fix: removed claim modal step and verified SHA number billing check

- packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.component.tsx
…leigible patients
*None.*
*None.*
*None.*
> fix: showing error message on failed eligibility verification for ineligible patients

- packages/esm-admin-app/src/components/users/manage-users/user-management.workspace.scss
- packages/esm-admin-app/src/components/users/manage-users/user-management.workspace.tsx
- packages/esm-admin-app/src/components/users/userManagementFormSchema.tsx
- packages/esm-admin-app/src/config-schema.ts
- packages/esm-admin-app/src/constants.ts
- packages/esm-admin-app/src/user-management.resources.ts
* Adds user role scope to the user management.
* Pick one of the selected roles to add operations and locations to add the user role scope.
* Refactor inventory roles category to additional roles
[userScope.webm](https://github.com/user-attachments/assets/6eaf88be-e578-44e7-95f6-e308be1bd201)
*None.*
*None.*
*None.*
> (feat): Add user role scope

- packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.component.tsx
A really simple fix to fix a sneaky bug because the API returns a status code of 1 if users are registered, whether or not they are active. so to separate `isActive` and `isRegistered` we check for status for the latter and whether or not the `coverageStartDate` and `coverageEndDate` are in range for `isActive`.
*None.*
*None.*
*None.*
> refactor: use sha status to check if user is registered

- packages/esm-providers-app/src/modal/provider-sync-modal.component.tsx
- packages/esm-providers-app/src/table/provider-details.component.tsx
- packages/esm-providers-app/src/workspace/provider-form.workspace.tsx
*None.*
see: https://thepalladiumgroup.atlassian.net/browse/KHP3-7315
*None.*
*None.*
> (feat) KHP3-7315: Follow up changes on HIE enhancement on the syncing of the providers attributes

- packages/esm-billing-app/src/routes.json
- packages/esm-version-app/src/app-navigation/home-root.component.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/create-dasboard-group.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/create-left-panel-link.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/create-patient-chart-dashboard-meta.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/dashboard-group-extension.component.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/index.ts
- packages/esm-version-app/src/app-navigation/nav-utils/link-extension.component.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/nav.scss
- packages/esm-version-app/src/app-navigation/nav-utils/patient-chart-dashboard.component.tsx
- packages/esm-version-app/src/app-navigation/nav-utils/utils.ts
- packages/esm-version-app/src/index.ts
- packages/esm-version-app/src/routes.json
https://github.com/user-attachments/assets/95c0f28d-be31-4fae-abaf-94113f0d9b72
https://thepalladiumgroup.atlassian.net/browse/KHP3-7349
https://thepalladiumgroup.atlassian.net/browse/KHP3-7348
*None.*
*None.*
> KHP3-7349-Implement Side navs and Nav groups with icons

- packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
This PR adds a link on `KenyaEMR modules` navbar section to view o3 reports
*None.*
*None.*
> (enhc) : Add link to reporting UI for o3

- packages/esm-billing-app/src/billable-services/billiable-item/order-actions/components/generic-button.component.tsx
- packages/esm-billing-app/src/billable-services/billiable-item/order-actions/components/medication-order-button.component.tsx
Fix an error when trying to pick lab orders
*None.*
*None.*
*None.*
> (fix) KHP3-7575 : Default modal name to lab order

- packages/esm-billing-app/src/claims/claims-management/main/claims-pre-auth-main.component.tsx
- packages/esm-billing-app/src/claims/claims-management/table/preauth-table.tmp.component.tsx
- packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
- Duplicated claims table code into preauth table to use claims info in preauth temporarily as we await preauth endpoint
https://github.com/user-attachments/assets/54d4a6e4-4361-49b7-85ce-eb42ca53869d
*None.*
*None.*
*None.*
> Replaced Preauth mock fhir data with claims endpoint data temporarily

- packages/esm-billing-app/translations/en.json
- packages/esm-morgue-app/src/card/avail-compartment.compartment.tsx
- packages/esm-morgue-app/src/extension/actionButton.component.tsx
- packages/esm-morgue-app/src/root.component.tsx
- packages/esm-morgue-app/src/routes.json
- packages/esm-morgue-app/src/tables/admitted-queue.component.tsx
- packages/esm-morgue-app/src/tabs/tabs.component.tsx
Initial setup of mortuary module privileges using the correct o3: prefix format.
This implementation ensures proper access control for the mortuary module features.
Changes include:
- Added "o3: View Mortuary Dashboard" for accessing the mortuary dashboard
- Added "o3: Swap Mortuary Compartments" for compartment swapping functionality
- Added "o3: Discharge Body from Mortuary" for body discharge operations
*None.*
*None.*
*None.*
> (feat) KHP3-7838 : Implement mortuary module priviliges with o3: prefix format

- packages/esm-facility-dashboard-app/src/surveillance/surveillance-dashboard.component.tsx
- packages/esm-facility-dashboard-app/src/surveillance/surveillance-filters.component.tsx
* Rename the KIP Tab name to Realtime gap review
* Rename the Monitoring chart tab to Progress tracker
* Rename High risk +ve PBFW not on PrEP to Highrisk -ve PBFW not enrolled to PrEP
*None.*
*None.*
*None.*
> (fix): KHP3-7944 Facility dashboard edits

- packages/esm-facility-dashboard-app/src/surveillance/charts/hiv-not-linked-to-art.component.tsx
* Fix the numerator for the HIV positive, not linked.
*None.*
*None.*
*None.*
> (fix): hiv positive not linked charts

- packages/esm-billing-app/src/claims/claims-management/table/claim-table.component.tsx
- packages/esm-billing-app/src/claims/claims-management/table/claims-list-table.component.tsx
- packages/esm-billing-app/src/claims/claims-management/table/preauth-table.tmp.component.tsx
- packages/esm-billing-app/src/claims/claims-management/table/use-facility-claims.ts
- packages/esm-billing-app/src/types/index.ts
- Implements filtering by `use` type in ClaimsTable component to properly separate claims from preauthorization records.
- Fixes the issue where claims and preauthorization records were mixed in the same table.
[Screencast from 10-06-2025 09:48:05 ALASIRI.webm](https://github.com/user-attachments/assets/7532eeb5-dab0-47c1-b171-33d12290f2d7)
*None.*
*None.*
*None.*
> (feat): Add use-type filtering to Claims Table component

- packages/esm-care-panel-app/src/patient-summary/patient-summary-body.component.tsx
KHP3-8036 Fix TPT not showing correctly in the Specialized clinics Hiv care summary page
*None.*
*None.*
*None.*
> KHP3-8036 Fix TPT not showing correctly in the Specialized clinics Hiv care summary page

- packages/esm-admin-app/src/routes.json
> fix: add left panel link missing for etls page

- package.json
- packages/esm-admin-app/package.json
- packages/esm-adr-app/package.json
- packages/esm-billing-app/package.json
- packages/esm-care-panel-app/package.json
- packages/esm-care-panel-app/src/patient-summary/patient-summary.component.test.tsx
- packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx
- packages/esm-cross-border-app/package.json
- packages/esm-facility-dashboard-app/package.json
- packages/esm-lab-manifest-app/package.json
- packages/esm-morgue-app/package.json
- packages/esm-pharmacy-app/package.json
- packages/esm-shr-app/package.json
- packages/esm-shr-app/src/shrpatient-summary/shrpatient-summary.component.tsx
- packages/esm-shr-app/translations/am.json
- packages/esm-shr-app/translations/en.json
- packages/esm-shr-app/translations/sw.json
- yarn.lock
This PR down-grades the version of react-to-print so the shared dependency affects other apps e.g `Dispensing`
*None.*
*None.*
*None.*
> fix : resolve printing issues that affect dispensing app

- packages/esm-billing-app/src/billable-services/billiable-item/drug-order/drug-order.component.tsx
This PR uses drugUuid to fetch price information for drugs. This should resolve error in displaying the wrong pricing information cc @andrineM @enyaencha 
https://github.com/user-attachments/assets/d61a06f4-971e-4599-b3ea-24fdb47b16d8
*None.*
*None.*
> fix : resolve price information to show correct price on drug order

- packages/esm-lab-manifest-app/src/index.ts
- packages/esm-lab-manifest-app/src/routes.json
- Restore lab manifest overview and listings on diagnostics
[Screencast from 2025-08-14 23-53-32.webm](https://github.com/user-attachments/assets/a1295493-a378-4e75-8410-47beb9eef1b9)
*None.*
*None.*
*None.*
> restore lab manifest links in diagnostics nav group
