palladiumkenya/kenyaemr-esm-3.x

package.json
packages/esm-patient-flags-app/src/hooks/usePatientFlags.tsx
packages/esm-patient-flags-app/src/kenyaemr-link/kenyaemr-link.test.tsx
yarn.lock

- Update swr to version 2.x and add unit test for KenyaEMR
*None.*
*None.*
*None.*

chore: update SWR to version 2.x and add KenyaEMR link unit test

---

packages/esm-patient-flags-app/src/hooks/usePatientId.tsx

(fix) Fixed build error

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/care-panel/care-panel.scss
packages/esm-care-panel-app/src/hooks/useEnrollmentHistory.ts
packages/esm-care-panel-app/src/index.ts
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.scss
packages/esm-care-panel-app/src/program-summary/program-summary.component.tsx
packages/esm-care-panel-app/src/types/index.ts

KHP3-3495 Add component for HIV care details

---

packages/esm-version-app/src/about/about.component.tsx
packages/esm-version-app/src/about/about.scss
packages/esm-version-app/src/frontend-modules/frontend-modules.component.tsx
packages/esm-version-app/src/hooks/useFrontendModules.tsx
packages/esm-version-app/src/index.ts
packages/esm-version-app/src/types/index.ts

- Detailed display of installed frontend assets
*None.*
*None.*
*None.*

(feat) display installed frontend assets

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/index.ts

https://www.loom.com/share/198130ecbab048ca95423b3b32d880dd?sid=19919497-7f17-4d26-b2cd-f124c9fb45a8
*None.*
*None.*
*None.*

(feat) Add patient summary in tabs

---

packages/esm-care-panel-app/package.json
packages/esm-care-panel-app/src/index.ts
packages/esm-care-panel-app/src/routes.json
packages/esm-patient-flags-app/package.json
packages/esm-patient-flags-app/src/index.ts
packages/esm-patient-flags-app/src/routes.json
packages/esm-version-app/package.json
packages/esm-version-app/src/index.ts
packages/esm-version-app/src/routes.json

* Add routes.json for patient-registration-app
* Bump openmrs and openmrs-esm-framework
* Bump peer deps and framework
*None.*
*None.*
*None.*

(BREAKING) Migrate all packages to use routes.json

---

packages/esm-care-panel-app/src/routes.json

Removed redundant summary slot
*None.*
*None.*
*None.*

(feat) Removed redundant summary slot

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
packages/esm-care-panel-app/src/program-summary/program-summary.component.tsx

(feat) Add empty string to variables that are not present

---

lerna.json
packages/esm-care-panel-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-version-app/package.json

Update version for releasing
*None.*
*None.*
*None.*

(chore) update to version 5

---

lerna.json
package.json
packages/esm-care-panel-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-version-app/package.json

- Update our versions for release on 8-July-2023
*None.*
*None.*
*None.*

(chore) Release `v5.1.0`

---

packages/esm-care-panel-app/package.json
packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/care-panel/care-panel.scss
packages/esm-care-panel-app/src/dashboard.meta.ts
packages/esm-care-panel-app/src/index.ts
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.scss
packages/esm-care-panel-app/src/program-summary/program-summary.scss
packages/esm-care-panel-app/src/routes.json
packages/esm-care-panel-app/webpack.config.js
yarn.lock

- Updated the UI with small changes
- Moved print-preview to the side panel
*None.*
*None.*
*None.*

(feat) Move  care-panel summary to side-nav and small UI improvements

---

packages/esm-version-app/package.json

(fix) patch version number

---

.env
.github/workflows/e2e.yml
.gitignore
e2e/README.md
e2e/core/global-setup.ts
e2e/core/index.ts
e2e/core/test.ts
e2e/fixtures/api.ts
e2e/fixtures/index.ts
e2e/pages/home-page.ts
e2e/pages/index.ts
e2e/specs/sample-test.spec.ts
package.json
playwright.config.ts

- The aim of this PR is to setup the playwright configuration and also to setup the github action to run the tests on pull request and on push. This includes a sample test as well.
*None.*
*None.*

Setup E2E test environment with playwright

---

packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx

Add tpt initiation date in tpt component
*None.*
*None.*
*None.*

Add tpt initiation date in tpt component

---

packages/esm-care-panel-app/package.json
packages/esm-patient-flags-app/src/clear-cache/cache-utils.ts
packages/esm-patient-flags-app/src/clear-cache/clear-cache.component.test.tsx
packages/esm-patient-flags-app/src/clear-cache/clear-cache.component.tsx
packages/esm-patient-flags-app/src/clear-cache/clear-cache.scss
packages/esm-patient-flags-app/src/index.ts
packages/esm-patient-flags-app/src/routes.json
yarn.lock

This PR add the "Reload & Clear Cache" function in the app menu for a streamlined user experience. This feature ensures users always access the most recent forms and content by effortlessly clearing outdated cache and reloading the content. It's a proactive step towards enhancing real-time content accessibility for our users.
*None.*
*None.*

(feat) Add app-menu shortcut to clear cache and reload to facilitate forms work

---

yarn.lock

Updated the core dependencies to the latest version this included the following.
-@openmrs/esm-framework
-@openmrs/esm-patient-common-lib
*None.*
*None.*
*None.*

(chore) Update core dependencies

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/hooks/useRegimenHistory.ts
packages/esm-care-panel-app/src/regimen/regimen-history.component.test.tsx
packages/esm-care-panel-app/src/regimen/regimen-history.component.tsx
packages/esm-care-panel-app/src/regimen/regimen-history.scss
packages/esm-care-panel-app/src/types/index.ts

Add regiment history

---

packages/esm-care-panel-app/src/program-summary/program-summary.component.tsx
packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx

Fix on saving arvs regimen

---

packages/esm-care-panel-app/src/regimen-editor/delete-regimen-modal.component.tsx
packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx

Fix rgimen workspace when deleting regimen

---

packages/esm-care-panel-app/src/regimen-editor/delete-regimen-modal.component.tsx
packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx

Mutate regimen encounter to properly show regimen buttons

---

packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx

Fix small typo

---

packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx
packages/esm-care-panel-app/src/types/index.ts

KHP3-4071 Add regimen dates in printable patient summary endpoint

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.test.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.scss
packages/esm-care-panel-app/src/program-summary/program-summary.component.tsx
packages/esm-care-panel-app/src/program-summary/program-summary.scss
packages/esm-care-panel-app/src/regimen-editor/regimen-button.component.tsx
packages/esm-care-panel-app/src/regimen-editor/standard-regimen.scss
packages/esm-care-panel-app/src/regimen/regimen-history.component.tsx
packages/esm-care-panel-app/src/regimen/regimen-history.scss

Re-organise care panel page display

---

packages/esm-care-panel-app/src/program-summary/program-summary.component.tsx
packages/esm-care-panel-app/src/program-summary/program-summary.test.tsx

- Updated the date on current status to the correct format
*None.*
*None.*
*None.*

(fix) Update date to correct format

---

packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx

Removed loading left erroneously in previous PR 
*None.*
*None.*
*None.*

(fix) Validating label should be displayed correctly

---

packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx
packages/esm-care-panel-app/src/regimen-editor/standard-regimen.scss

Enhance regimen for styles
*None.*
*None.*
*None.*

(refactor) Enhance regimen for styles

---

__mocks__/patient-summary.mock.ts
packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx

Fixed date formats in printable patient summary
*None.*
*None.*
*None.*

(fix) Fixed date formats in printable patient summary

---

packages/esm-billing-app/src/bills-table/bills-table.component.tsx
packages/esm-billing-app/src/invoice/invoce.component.tsx
packages/esm-billing-app/src/invoice/invoice.scss
packages/esm-billing-app/src/root.component.tsx

(feat) Add patient banner on invoice page

---

packages/esm-billing-app/src/invoice/invoice-table.component.tsx
packages/esm-billing-app/src/invoice/invoice-table.scss
packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/payments/payment-methods.scss
packages/esm-billing-app/src/invoice/payments/payment-options.component.tsx
packages/esm-billing-app/src/invoice/payments/payments.component.tsx
packages/esm-billing-app/src/invoice/payments/payments.scss

(feat) Add invoice details page

---

packages/esm-billing-app/src/bill-history/bill-history.component.tsx
packages/esm-billing-app/src/bill-history/bill-history.scss
packages/esm-billing-app/src/billing.resource.ts
packages/esm-billing-app/src/bills-table/bills-table.component.tsx
packages/esm-billing-app/src/dashboard.meta.ts
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/metrics-cards/metrics-cards.component.tsx
packages/esm-billing-app/src/routes.json
packages/esm-billing-app/src/types/index.ts

- Add patient billing history extension
*None.*
*None.*
*None.*

(feat) Add patient billing history extension

---

packages/esm-billing-app/src/invoice/invoice-table.component.tsx
packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/invoice.scss
packages/esm-billing-app/src/invoice/payments/payments.scss

Add payment breakdown section
*None.*
*None.*
*None.*

(feat) Add payment breakdown section

---

.github/workflows/ci.yml
e2e/README.md

Just moves some environment variables around.
*None.*
*None.*
*None.*

(chore) Minimal Github Actions workflow refactors

---

packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/invoice.scss

I've made a few tweaks to the invoice details header to align with the designs.
> Before
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8509731/57a1db26-9254-4f4e-bb8e-e55278e1719e
> After
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8509731/67bf34fc-fda1-43cf-8600-d0f8366d7f7a
*None*
*None*

(fix) Invoice details header UI tweaks

---

packages/esm-billing-app/src/index.ts
packages/esm-care-panel-app/src/index.ts
packages/esm-patient-clinical-view-app/src/index.ts
packages/esm-patient-flags-app/src/index.ts
packages/esm-shr-app/src/index.ts
packages/esm-version-app/src/index.ts

I've amended component imports in app entry points for frontend modules in this monorepo to opt into a [performance optimization](https://o3-docs.openmrs.org/docs/migration-guide#6-tweak-component-imports-to-limit-the-number-of-webpack-chunks-created) introduced recently in O3. 
We use Webpack to bundle our frontend code. Webpack splits our code into small units called chunks as a performance optimization to try and reduce the amount of JavaScript files that need to get downloaded. The way the chunking algorithm works is that, loosely, each time we create a dynamic import like:
```ts
export const patientProgramSummary = getAsyncLifecycle(() => import('./care-panel/care-panel.component'), options);
```
Webpack creates a new chunk for that file. This means that the more dynamic imports you …

(perf) Use fewer dynamic imports to load apps

---

packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
packages/esm-billing-app/src/billing-form/billing-checkin-form.scss
packages/esm-billing-app/src/billing-form/billing-checkin-form.test.tsx
packages/esm-billing-app/src/billing-form/billing-form.resource.tsx
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json

This PR adds ability to bill a patient upon check in on the start visit
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/649a87eb-1b1c-4997-bd30-a470a7dd82ed
*None.*
@ojwanganto @makombe @jecihjoy   might want to have a look

(feat) Add ability to bill patient on check in

---

packages/esm-billing-app/src/billing.resource.ts
packages/esm-billing-app/src/bills-table/bills-table.component.tsx
packages/esm-billing-app/src/bills-table/bills-table.scss
packages/esm-billing-app/src/constants.ts

This PR adds ability to sort bills by `dateCreate` with the latest bills appearing first. I have also include functionality to filter by payment status i.e `PAID` `PENDING` and 'ALL` see the screen recording below.
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/ba0d30f1-9f8b-4644-aadd-88e963db266e
*None.*
*None.*

(feat) filter bills to display pending bill and sort by date Created

---

packages/esm-billing-app/src/invoice/printable-invoice/printable-footer.component.tsx
packages/esm-billing-app/src/invoice/printable-invoice/printable-footer.scss
packages/esm-billing-app/src/invoice/printable-invoice/printable-invoice-header.component.tsx
packages/esm-billing-app/src/invoice/printable-invoice/printable-invoice-header.scss
packages/esm-billing-app/src/invoice/printable-invoice/printable-invoice.component.tsx
packages/esm-billing-app/src/invoice/printable-invoice/printable-invoice.scss

I've made some UI improvements to the bill invoice print preview to better align it with the available designs.
> Before
> After
*None.*
*None.*

(feat) Print preview UI

---

README.md

Update README 03 documentation
*None.*
*None.*
*None.*

(chore) Updae README Project documentation link

---

packages/esm-billing-app/src/billable-services-admin-card-link.component.test.tsx
packages/esm-billing-app/src/billable-services-admin-card-link.component.tsx
packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
packages/esm-billing-app/src/billable-services/billable-services-home.component.tsx
packages/esm-billing-app/src/billable-services/billable-services.component.tsx
packages/esm-billing-app/src/billable-services/billable-services.scss
packages/esm-billing-app/src/billable-services/billable-services.test.tsx
packages/esm-billing-app/src/billable-services/dashboard/dashboard.component.tsx
packages/esm-billing-app/src/billable-services/dashboard/dashboard.scss
packages/esm-billing-app/src/billable-services/dashboard/dashboard.test.tsx
packages/esm-billing-app/src/billable-services/dashboard/service-metrics.component.tsx
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json
packages/esm-billing-app/translations/en.json

(feat) Setup billable services app

---

packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/invoice.scss
packages/esm-billing-app/src/invoice/printable-invoice/print-receipt.component.tsx
packages/esm-billing-app/src/invoice/printable-invoice/print-receipt.scss
packages/esm-billing-app/translations/en.json

- Add printable receipt component
- https://www.loom.com/share/361f15d43d8a41e486d406abdd882fdc?sid=0a5576c7-fca8-452d-abc8-4a4754bbfd38
*None.*
*None.*
*None.*

(feat) Add print receipt button

---

jest.config.js
packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
packages/esm-billing-app/src/billable-services/billable-services-home.component.tsx
packages/esm-billing-app/src/billable-services/billable-services.component.tsx
packages/esm-billing-app/src/billable-services/billable-services.scss
packages/esm-billing-app/src/billable-services/billable-services.test.tsx
packages/esm-billing-app/src/billable-services/dashboard/dashboard.component.tsx
packages/esm-billing-app/src/billable-services/dashboard/dashboard.scss
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/translations/en.json

(feat) Billable services dashboard

---

packages/esm-patient-flags-app/src/navbar/navbar-action-button.test.tsx
packages/esm-patient-flags-app/src/navbar/navbar-overlay.component.tsx
packages/esm-patient-flags-app/translations/en.json

Update empty state message and also updated the test associated with this change.
*None.*
*None.*
*None.*

(fix) update empty state message on search navbar links

---

__mocks__/encounter-observations.mock.ts
packages/esm-patient-clinical-view-app/src/data-table/o-table.component.test.tsx
packages/esm-patient-clinical-view-app/src/data-table/o-table.component.tsx

- Add tests for base table
*None.*
*None.*
*None.*

(tests) Add base table component table tests

---

__mocks__/encounter-observation.mock.ts
packages/esm-patient-clinical-view-app/src/encounter-list/encounter-list.component.test.tsx
packages/esm-patient-clinical-view-app/src/encounter-list/encounter-list.component.tsx
packages/esm-patient-clinical-view-app/src/encounter-list/encounter-list.scss
packages/esm-patient-clinical-view-app/src/encounter-observation/encounter-observation.component.tsx
packages/esm-patient-clinical-view-app/src/esm-mch-app/views/maternal-health/maternal-health.test.tsx
packages/esm-patient-clinical-view-app/src/hooks/useEncounterRows.ts
packages/esm-patient-clinical-view-app/translations/en.json

- Add encounter list tests and refactored code
*None.*
*None.*
*None.*

(tests) Add encounter list tests and refactored code

---

e2e/specs/billing/billling-history.spec.ts
example.env
packages/esm-billing-app/src/invoice/invoice.test.tsx
packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.component.tsx
packages/esm-billing-app/src/invoice/payments/payments.component.tsx

This PR adds a fix for bill payment, this ensures the amount to be paid doesn't exceed the bill amount. In addition i have also improved test covering `billing-histrory`
*None.*
*None.*
*None.*

(fix) Add validation on payment amount and improved billing history e2e test

---

packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.scss

This fixes a regression in the bill line items table search input by removing a global style declaration and replacing it with a scoped class name. 
> Before
> After
*None.*
*None.*

(fix) Fix line items search input UI

---

__mocks__/bills.mock.ts
packages/esm-billing-app/src/invoice/invoice-table.component.tsx
packages/esm-billing-app/src/invoice/invoice.test.tsx
packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.component.tsx

This just cleans up the invoice component test suite, drying up some stuff and getting rid of cruft.
*None.*
*None.*
*None.*

(refactor) Clean up Invoice component test suite

---

packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx

(fix) Avoid creation of bills without item prices

---

packages/esm-billing-app/src/invoice/payments/invoice-breakdown/invoice-breakdown.component.tsx
packages/esm-billing-app/src/invoice/payments/invoice-breakdown/invoice-breakdown.scss
packages/esm-billing-app/src/invoice/payments/payments.component.tsx

[Screencast from 19-01-2024 02:03:49 ASUBUHI.webm](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/18227275/63947f61-2a7a-4888-af72-4fa21be5115a)
*None.*
*None.*
*None.*

(fix) flag overpayment during bill settlement

---

packages/esm-patient-clinical-view-app/src/clinical-view-group/createDashboardGroup.tsx
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/mch-dashboard.meta.tsx
packages/esm-patient-clinical-view-app/src/special-clinics/hiv-care-and-treatment-services/hiv-care-and-treatment-dashboard.meta.tsx
packages/esm-patient-clinical-view-app/src/utils/expression-helper.ts

This PR create ability to conditionally display `Clinical views` based on an expression. In the attached video i have configured the following rules.
1. Maternal and Child Health should only be displayed for `female` patients and `enrolled to ` either MCH Child or Mother services
2. HIV Care and Treatment should be displayed only for patients enrolled to `HIV` care program
The logic used for this is shown below for both scenarios.
**HIV**
```tsx
export const hivCareAndTreatmentNavGroup = {
title: 'HIV Care & Treatment',
slotName: 'hiv-care-and-treatment-slot',
isExpanded: true,
isChild: true,
showWhenExpression: "enrollment.includes('HIV')",
};
```
The expression `showWhenExpression` dictates when this component is to be displayed.
**MCH Child or Mother Service**
```tsx
export const …
```

(feat) Add ability to dynamically hide/display clinical views

---

packages/esm-billing-app/src/bill-history/bill-history.component.tsx
packages/esm-billing-app/src/billable-services/bill-waiver/utils.ts
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
packages/esm-billing-app/src/bills-table/bills-table.component.tsx
packages/esm-billing-app/src/invoice/invoice-table.component.tsx
packages/esm-billing-app/src/invoice/payments/utils.ts

Fix issue with bill item display after payment

---

packages/esm-patient-clinical-view-app/src/clinical-encounter/clinical-encounter-dashboard-meta.tsx
packages/esm-patient-clinical-view-app/src/clinical-view-group/createDashboardGroup.tsx
packages/esm-patient-clinical-view-app/src/clinical-view-group/dashboard-group.component.tsx
packages/esm-patient-clinical-view-app/src/clinical-view-group/dashboard-group.scss
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/mch-dashboard.meta.tsx
packages/esm-patient-clinical-view-app/src/special-clinics/hiv-care-and-treatment-services/hiv-care-and-treatment-dashboard.meta.tsx
packages/esm-patient-clinical-view-app/src/special-clinics/special-clinic-dashboard.meta.tsx
packages/esm-patient-clinical-view-app/src/utils/expression-helper.ts

This PR introduces optimizations for left-side NavGroup expression evaluation, enhances hierarchy visualization through improved indentation, and sets NavGroups to collapse by default for a cleaner, more efficient navigation experience.
Notice that `HIV Care & Treatment` is correctly indented.
*None.*
*None.*

(feat) Optimize expression evaluation and enhance UI indentation in left side NavGroup

---

packages/esm-billing-app/src/bill-history/bill-history.component.tsx
packages/esm-billing-app/src/billable-services/bill-waiver/bill-selection.component.tsx
packages/esm-billing-app/src/billable-services/bill-waiver/patient-bills.component.tsx
packages/esm-billing-app/src/helpers/functions.ts
packages/esm-billing-app/src/invoice/payments/payments.component.tsx
packages/esm-billing-app/src/invoice/payments/utils.ts
packages/esm-billing-app/src/modal/require-payment-modal.component.tsx

(enhc) update bill history page navigation and add extractstring function

---

packages/esm-billing-app/src/billing.resource.ts
packages/esm-billing-app/src/invoice/invoice-table.component.tsx
packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/payments/utils.ts
packages/esm-billing-app/src/types/index.ts

(fix) Update payment to support partial payments and updating payment status correctly

---

packages/esm-billing-app/src/invoice/payments/utils.ts

(fix) update pending bills

---

packages/esm-billing-app/src/billable-services/bill-waiver/utils.ts
packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
packages/esm-billing-app/src/billing-form/billing-checkin-form.test.tsx
packages/esm-billing-app/src/billing-form/billing-form.resource.tsx
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
packages/esm-billing-app/src/constants.ts
packages/esm-billing-app/src/invoice/payments/payment.resource.ts
packages/esm-billing-app/src/invoice/payments/payments.component.tsx

(chore) remove hard coded attribute and concept uuids

---

lerna.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

(release) Update to version 5.1.1

---

packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx

This PR fixes a typo on additional props passed to form engine.
*None.*
*None.*
*None.*

(fix) fix typo on the enrollmentDetails additional props for form engine

---

packages/esm-shr-app/src/community-referrals/referral-reasons/referral-reasons.component.scss
packages/esm-shr-app/src/community-referrals/referral-reasons/referral-reasons.component.tsx
packages/esm-shr-app/src/community-referrals/referrals-actions.component.tsx

(fix)View reasons dialog box

---

packages/esm-shr-app/src/community-referrals/community-referrals.component.tsx
packages/esm-shr-app/src/community-referrals/referral-reasons/referral-reasons.component.tsx
packages/esm-shr-app/src/community-referrals/referrals-actions.component.tsx

- View Reasons in the complete tab
- 
*None.*
*None.*

Fx view patient details

---

package.json
packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
packages/esm-billing-app/src/billing-prompt/billing-prompt.resource.tsx
yarn.lock

(fix) fix error on billing prompt showing for exempted patients

---

packages/esm-shr-app/src/community-referrals/community-referrals.component.tsx

(fix) Fixed typo error on referred

---

packages/esm-shr-app/src/community-referrals/referrals-actions.component.tsx

Fix typo on success snackbar

---

packages/esm-patient-clinical-view-app/src/clinical-encounter/summary/out-patient-summary/patient-medical-history.component.tsx
packages/esm-patient-clinical-view-app/src/clinical-encounter/summary/out-patient-summary/patient-social-history.component.tsx
packages/esm-shr-app/translations/en.json

(feat) Add mutation upon submission of clinical encounter for flags

---

packages/esm-claims-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx

Correctly translate phone number place holder for bill payment

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/index.ts
packages/esm-patient-clinical-view-app/src/routes.json
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/encounter-observations/encounter-observations.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/encounter-observations/styles.scss
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/generic-dashboard.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/generic-nav-links.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/useEncounters.tsx
packages/esm-patient-clinical-view-app/src/ui/encounter-list/encounter.resource.tsx
packages/esm-patient-clinical-view-app/translations/en.json

https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/31633b3f-15c1-43ec-8cd5-c412658d3941
*None.*
*None.*
*None.*

(feat) Add special clinic with support for configuration

---

yarn.lock

(fix) fix build error after merge of morgue error

---

packages/esm-billing-app/package.json
packages/esm-billing-app/src/bill-history/bill-history.component.tsx
packages/esm-care-panel-app/package.json
packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx
packages/esm-care-panel-app/src/regimen-editor/regimen-button.component.tsx
packages/esm-claims-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-clinical-view-app/src/clinical-encounter/dashboard/clinical-encounter-dashboard.component.tsx
packages/esm-patient-clinical-view-app/src/clinical-encounter/summary/in-patient-medical-summary/in-patient-medical-summary.component.tsx
packages/esm-patient-clinical-view-app/src/clinical-encounter/summary/out-patient-summary/patient-medical-history.component.tsx
packages/esm-patient-clinical-view-app/src/family-partner-history/family-history.component.tsx
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/partography/partograph.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/generic-dashboard.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/hiv-care-and-treatment-services/defaulter-tracing/defaulter-tracing.component.tsx
packages/esm-shr-app/package.json
packages/esm-version-app/src/release-version.js
yarn.lock

(fix) KHP3-5630:Update kenyaemr packages to align with recent changes for workspaces and resolve common-lib errors

---

jest.config.js
package.json
packages/esm-billing-app/src/billable-services-admin-card-link.component.test.tsx
packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
packages/esm-billing-app/src/billable-services/billable-services.test.tsx
packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.component.tsx
packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.test.tsx
packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.component.tsx
packages/esm-care-panel-app/src/care-programs/care-programs.test.tsx
yarn.lock

(fix) Update test and fix error on deleting wrong method of payment

---

packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
packages/esm-care-panel-app/src/care-programs/care-programs.test.tsx
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx

(fix) Allow launching of forms

---

packages/esm-billing-app/src/billing-form/billing-form.component.tsx
packages/esm-billing-app/translations/en.json

https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/7160e393-b234-4abd-abe7-328b29f7cf51
*None.*
*None.*
*None.*

(fix) Fix failing billing form on saving service or stock item

---

packages/esm-billing-app/src/billing.resource.ts

Update bill resource to fetch current date bills on billing dashboard
*None.*
*None.*
*None.*

(feat) default billing dashboard bills to current date

---

packages/esm-billing-app/src/billable-services/bill-waiver/bill-waiver-form.component.tsx
packages/esm-billing-app/src/billing-form/billing-form.resource.tsx
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx

Enhance exclusion of payment methods
*None.*
*None.*
*None.*

(feat) enhance exclusion of payment methods

---

packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/generic-dashboard.component.tsx

Update patient workspace form for special clinics
*None.*
*None.*
*None.*

(fix) Update patient workspace form for special clinics

---

packages/esm-care-panel-app/src/regimen-editor/delete-regimen-modal.component.tsx
packages/esm-care-panel-app/src/regimen-editor/regimen-form.component.tsx

Fix date navigagiton issue on regiment events

---

packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.component.tsx
packages/esm-billing-app/src/invoice/payments/payments.test.tsx

see https://thepalladiumgroup.atlassian.net/browse/KHP3-5784
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/4a75ce49-374f-495f-b006-c870a43c4718
*None.*
*None.*

(feat) KHP3-5784: Improve auto-focus behavior for adding method of payment

---

packages/esm-billing-app/src/billing-form/billing-form.component.tsx

Fix undefined price on billable seriveces during search

---

packages/esm-billing-app/src/billing-form/billing-form.component.tsx

Remove static price for stock items

---

packages/esm-billing-app/src/invoice/payments/payment-history/payment-history.component.tsx
packages/esm-billing-app/src/invoice/payments/payments.component.tsx

…fter successful bill payment
*None.*
*None.*
*None.*

(enhc) remove bill amount item on patients table and prevent page redirect after successful bill payment

---

lerna.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

Update to v5.2.0
*None.*
*None.*
*None.*

(release) update to version v5.2.0

---

packages/esm-patient-clinical-view-app/src/contact-list/contact-list.resource.tsx
packages/esm-patient-clinical-view-app/src/types/index.ts
packages/esm-patient-clinical-view-app/translations/en.json

Map concept id values for attributes to actual names for contact listing

---

packages/esm-billing-app/src/routes.json
packages/esm-care-panel-app/src/routes.json
packages/esm-patient-clinical-view-app/src/routes.json
packages/esm-patient-flags-app/src/routes.json
packages/esm-version-app/src/routes.json

This follows https://github.com/palladiumkenya/openmrs-module-kenyaemr/pull/1939 that updates `kenyaemr` backend to version 19
*None.*
*None.*
*None.*

(chore) update `kenyaemr` version to 19

---

packages/esm-billing-app/src/invoice/payments/payments.component.tsx

(revert) navigate to dashboard once payment is made

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/contact-list/contact-actions.component.tsx
packages/esm-patient-clinical-view-app/src/contact-list/contact-list.component.tsx
packages/esm-patient-clinical-view-app/src/contact-list/contact-list.resource.tsx
packages/esm-patient-clinical-view-app/src/contact-list/contact-list.workspace.tsx
packages/esm-patient-clinical-view-app/src/contact-list/hiv-status.component.tsx
packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
packages/esm-patient-clinical-view-app/src/hooks/useRelationshipTypes.ts
packages/esm-patient-clinical-view-app/src/hooks/useRelativeHTSEncounter.ts
packages/esm-patient-clinical-view-app/src/hooks/useRelativeHivEnrollment.ts
packages/esm-patient-clinical-view-app/src/utils/expression-helper.ts

- Seperated cooncerns by mocing contact listing related hooks out of contact list resources
- Removed Actions from contact list table
*None.*
*None.*
*None.*

Clean contact list

---

packages/esm-billing-app/src/billing-dashboard/billing-dashboard.component.tsx
packages/esm-billing-app/src/billing-tabs/billling-tabs.component.tsx
packages/esm-billing-app/src/invoice/payments/payments.component.tsx
packages/esm-billing-app/src/past-patient-bills/filtered-patient-bills.component.tsx
packages/esm-billing-app/src/past-patient-bills/patient-bills-dashboard/patient-bills-dashboard.scss
packages/esm-billing-app/src/past-patient-bills/patient-bills-dashboard/patient-bills-dashboard.tsx
packages/esm-billing-app/src/past-patient-bills/patient-bills.scss

Uploading BILLING TABS AND SEARCH.mp4…
*None.*
*None.*
*None.*

(feat) : added billing tabs and search option for patient bills

---

tools/setupTests.ts

This fix should resolve the failing test
*None.*
*None.*
*None.*

(fix) fix broken unit test on billing dashboard

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/contact-list/birthdate-calculator.component.tsx
packages/esm-patient-clinical-view-app/src/contact-list/contact-list.workspace.tsx
packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts

- Contact relationships filtered for only family eliminating patient provider relationships
- Used showSnackbar for notification in place of showNortification
*None.*
*None.*

(feat) filter contact list by relationship type and use snackbar for notifications

---

packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
packages/esm-billing-app/translations/en.json

summary:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6172
*None.*
*None.*
*None.*

KHP3-6172 - (Refactor)  Billing/checkin form

---

packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx

(feat) remove 'regimen' and 'regimen change reason' columns from enrollment history table

---

yarn.lock

simple fix for yarn lock file
*None.*
*None.*
*None.*

(fix) update `yarn.lock` file to fix broken ci

---

packages/esm-billing-app/src/billable-services/bill-manager/bill-manager.scss
packages/esm-billing-app/src/billable-services/bill-manager/modals/cancel-bill.scss
packages/esm-billing-app/src/billable-services/bill-manager/modals/refund-bill.modal.tsx
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/types/index.ts

In this PR I have fixed all the issues raised on #296 code review . I now use carbon modules for colors and spacing as suggested. Also this [here](https://github.com/amosmachora/kenyaemr-esm-3.x/blob/a1f0c6f2f8ef4ff068bf035edbdb327d60199570/packages/esm-billing-app/src/billable-services/bill-manager/bill-manager.scss#L17) I have no option there is an overriding style from the carbon design system that is too specific to override.
Feedback will be appreciated.
*None.*
*None.*
*None.*

(refactor) : applied changes from code review

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
packages/esm-care-panel-app/src/hooks/useCarePrograms.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/hiv-care-and-treatment-services/defaulter-tracing/defaulter-tracing.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/hiv-care-and-treatment-services/defaulter-tracing/defaulter-tracing.scss

See https://thepalladiumgroup.atlassian.net/browse/KHP3-6309
*None.*
*None.*

(feat) : KHP3-6309 : enable clinical views for patient who have ever been enrolled to a specific program

---

packages/esm-billing-app/src/routes.json
packages/esm-care-panel-app/translations/en.json

This fixes an error introduced by this [PR](https://github.com/palladiumkenya/kenyaemr-esm-3.x/pull/308)
*None.*
*None.*
*None.*

(fix) : restore billing link on home dashboard page

---

packages/esm-billing-app/src/billable-services/bill-manager/bill-line-items.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-form.test.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-form.workspace.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill-util.ts
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill.scss

See https://thepalladiumgroup.atlassian.net/browse/KHP3-6442
https://github.com/user-attachments/assets/86c3f574-f350-4dd9-a9da-ac9bd713f1fc
*None.*
*None.*

(fix) : KHP3-6442 : Fix error on editing a bill lineItem

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/in-patient/encounter-observations/encounter-observations.component.tsx
packages/esm-patient-clinical-view-app/src/in-patient/encounter-observations/index.ts
packages/esm-patient-clinical-view-app/src/in-patient/encounter-observations/styles.scss
packages/esm-patient-clinical-view-app/src/in-patient/encounter-observations/visit.resource.tsx
packages/esm-patient-clinical-view-app/src/in-patient/in-patient-table/in-patient-table.component.tsx
packages/esm-patient-clinical-view-app/src/in-patient/in-patient-table/in-patient-table.scss
packages/esm-patient-clinical-view-app/src/in-patient/in-patient.component.tsx
packages/esm-patient-clinical-view-app/src/in-patient/in-patient.meta.tsx
packages/esm-patient-clinical-view-app/src/in-patient/in-patient.resource.tsx
packages/esm-patient-clinical-view-app/src/index.ts
packages/esm-patient-clinical-view-app/src/routes.json
packages/esm-patient-clinical-view-app/src/summary/summary.component.tsx
packages/esm-patient-clinical-view-app/src/summary/summary.resource.ts
packages/esm-patient-clinical-view-app/src/summary/summary.scss
packages/esm-patient-clinical-view-app/src/types/index.ts
packages/esm-patient-clinical-view-app/src/ward-card/ward-card.component.tsx
packages/esm-patient-clinical-view-app/src/ward-card/ward-card.scss

This PR migrates @donaldkibet `s work on  this [PR ](https://github.com/palladiumkenya/esm-ugandaemr-bed-management-app/pull/8)to kenyaemr3.x
see https://thepalladiumgroup.atlassian.net/browse/KHP3-6307
*None.*
*None.*
*None.*

(feat): moved in patient functionality from esm-ugandaemr-bed-management-app to kenyaemr-esm-3.x

---

packages/esm-billing-app/src/billable-services/bill-manager/modals/refund-bill.modal.tsx

This PR fixes an issue with posting refunds for bill captured in error.
https://github.com/user-attachments/assets/82df895b-9099-469b-857a-92ba41fd6e4c
*None.*
*None.*

(fix) : fix error on posting bill re-fund

---

packages/esm-billing-app/src/billing-form/billing-form.component.tsx
packages/esm-billing-app/src/billing-form/billing-form.scss
packages/esm-billing-app/src/billing.resource.ts

See https://thepalladiumgroup.atlassian.net/browse/KHP3-6462
*None.*
*None.*

(fix) KHP3-6463 : prevent creation of bills with price set to zero

---

packages/esm-billing-app/src/billing-form/billing-form.scss
packages/esm-billing-app/src/routes.json
packages/esm-billing-app/translations/en.json

Simple PR to hide WIP for HIE(Health Information Exchange) under one feature flag.
*None.*
*None.*
*None.*

(feat) : hide benefits package dashboard under (hie) feature flag

---

packages/esm-billing-app/src/billable-services/billable-services-home.component.tsx
packages/esm-billing-app/src/billable-services/billable-services.component.tsx
packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.scss
packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.workspace.tsx
packages/esm-billing-app/src/billable-services/dashboard/dashboard.component.tsx
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json
packages/esm-billing-app/translations/en.json

Converted editing billable service form from overlay to workspace
[screen-capture (6).webm](https://github.com/user-attachments/assets/5a944ff2-395d-471c-8d60-11a685736763)
*None.*
*None.*

(fix) converted editing billable service form from overlay to workspace

---

packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.component.tsx
packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.test.tsx

[Screencast from 22-08-2024 08:44:13 ASUBUHI.webm](https://github.com/user-attachments/assets/578c44b5-eda1-40e4-8843-0eaeed8cd21c)
*None.*
*None.*

Fix not able to add billable services

---

packages/esm-version-app/src/about/about.component.tsx
packages/esm-version-app/src/hooks/useSystemSetting.tsx
packages/esm-version-app/src/types/index.ts

*None.*
https://thepalladiumgroup.atlassian.net/browse/KHP3-6482
*None.*
*None.*

Khp3 6482 added facility sha accreditation information on system info

---

packages/esm-patient-flags-app/src/hooks/useDefaultFacility.ts
packages/esm-patient-flags-app/src/navbar/navbar-link.component.tsx
packages/esm-patient-flags-app/src/navbar/navbar-link.scss
packages/esm-patient-flags-app/src/types/index.ts
packages/esm-version-app/src/about/about.component.tsx

https://github.com/user-attachments/assets/8c846bdf-cb40-414b-987c-ca3179622a3f
https://github.com/user-attachments/assets/978a8d3e-11dc-46b7-bcfc-a69802afc181
https://thepalladiumgroup.atlassian.net/browse/KHP3-6483
*None.*

Khp3 6483 add facility sha accreditation expiry warning notification

---

packages/esm-patient-flags-app/src/navbar/navbar-link.component.tsx
packages/esm-version-app/src/about/about.component.tsx

*None.*
https://thepalladiumgroup.atlassian.net/browse/KHP3-6487
*None.*

Showing waning notification based on operational status

---

packages/esm-billing-app/src/billable-services/manage-commodity-price/workspaces/edit-purchase-price-form.workspace.tsx

Fix error editing commodity price

---

packages/esm-billing-app/src/billable-services/billiable-item/test-order/imaging-order.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/test-order/lab-order.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/test-order/price-info-order.componet.tsx
packages/esm-billing-app/src/billable-services/billiable-item/test-order/procedure-order.component.tsx
yarn.lock

*None.*
*None.*
*None.*
see: https://thepalladiumgroup.atlassian.net/browse/KHP3-6491

KHP3-6491: Fixed bug reverting the rendering condition on orders

---

packages/esm-patient-flags-app/src/config-schema.ts
packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
packages/esm-patient-flags-app/src/navbar/navbar-action-button.component.tsx
packages/esm-patient-flags-app/src/navbar/navbar-overlay.component.tsx

This PR aims to streamline links on `KenyaEMR Modules` on primary navigation bar to comply with roles assigned to users. cc @Murithijoshua will this address concerns of seeing the links? give it a test and let me know. Thanks!
In Addition also make the facility dashboard configurable.
*None.*
*None.*

(feat) : KHP3-5781 add privilege level control on modules

---

packages/esm-patient-clinical-view-app/src/config-schema.ts

Use correct form and encounter type uuid for home visit checklist form

---

packages/esm-billing-app/src/hooks/useRequestStatus.tsx
packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
packages/esm-billing-app/src/invoice/payments/utils.ts

This PR adds the functionality to automatically add the paid mpesa amount to the bill tendered amount.
https://github.com/user-attachments/assets/dcfd7c5e-7d94-4ce8-9ce1-b487c7d9bec5
*None.*
cc @ojwanganto

(feat) : mutate bills on successful mpesa payment

---

packages/esm-billing-app/src/billable-services/bill-manager/bill-manager.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/patient-bills.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill-form.test.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill-form.workspace.tsx
packages/esm-billing-app/src/billable-services/billables/charge-summary-table.component.tsx
packages/esm-billing-app/src/billable-services/billables/charge-summary.resource.tsx
packages/esm-billing-app/src/billable-services/billables/form-helper.ts
packages/esm-billing-app/src/billable-services/billables/services/price.component.tsx
packages/esm-billing-app/src/billing-form/billing-form.component.tsx
packages/esm-billing-app/src/billing.resource.ts
packages/esm-billing-app/src/config-schema.ts
packages/esm-billing-app/translations/en.json

- Close waiver form after posting a waiver
- Remove already added method of payment on billable forms
- Update exemption config to take the correct Type
- Set the correct form title for Editing billable items
- Chargeable table should search items correctly now together with editing the correct row
- Ensure pagination works as expected.
*None.*
*None.*
*None.*

(feat) : code enhancement on billing and config update

---

lerna.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-providers-app/package-lock.json
packages/esm-providers-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

Update to v5.3.0 for patch release. cc @ojwanganto @RAJABIBRAZ @andrineM 
*None.*
*None.*
*None.*

(release) v5.3.0

---

lerna.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-providers-app/package-lock.json
packages/esm-providers-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

Update to v5.3.2
*None.*
*None.*
*None.*

(release) v5.3.2

---

packages/esm-patient-clinical-view-app/src/case-management/encounters/case-encounter-header.scss
packages/esm-patient-clinical-view-app/src/case-management/encounters/case-encounter-overview.component.tsx
packages/esm-patient-clinical-view-app/src/specialized-clinics/generic-nav-links/generic-table.component.tsx
packages/esm-pharmacy-app/src/pharmacy-header/pharmacy-header.component.tsx
packages/esm-pharmacy-app/translations/en.json

https://github.com/user-attachments/assets/37e9b0f8-9fb9-4d4f-a2bd-3ed49859df75
https://thepalladiumgroup.atlassian.net/browse/KHP3-6526
*None.*

KHP3-6526-fix-case-management-encounter-layout-and-pagination

---

package.json

(chore) : set version number

---

packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts

https://thepalladiumgroup.atlassian.net/browse/KHP3-6536
*None.*

KHP3-6536-fix-pns-relationship-failure-to-display-all-contact-recorded-information-informationn pns contacts

---

packages/esm-patient-clinical-view-app/src/contact-list/contact-list.component.tsx
packages/esm-patient-clinical-view-app/src/family-partner-history/family-history.component.tsx
packages/esm-patient-clinical-view-app/src/family-partner-history/relationships.resource.tsx
packages/esm-patient-clinical-view-app/src/hooks/useRelationship.ts
packages/esm-patient-clinical-view-app/src/hooks/useRelationshipTypes.ts
packages/esm-patient-clinical-view-app/src/index.ts
packages/esm-patient-clinical-view-app/src/other-relationships/other-relationships.component.tsx
packages/esm-patient-clinical-view-app/src/relationships/forms/form.scss
packages/esm-patient-clinical-view-app/src/relationships/forms/relationships-update-form.workspace.tsx
packages/esm-patient-clinical-view-app/src/relationships/relationship.resources.ts
packages/esm-patient-clinical-view-app/src/routes.json
packages/esm-patient-clinical-view-app/src/types/index.ts

https://github.com/user-attachments/assets/c45a5459-8a13-479e-823f-6d89d9a41d86
https://thepalladiumgroup.atlassian.net/browse/KHP3-6575
*None.*

Khp3 6575 add ability to edit the relationship details once a relationship form has been saved

---

packages/esm-lab-manifest-app/src/header/lab-manifest-header.scss
packages/esm-lab-manifest-app/src/metrics/lab-manifest-metrics.scss

https://thepalladiumgroup.atlassian.net/browse/KHP3-6559
*None.*

Khp3 6559 refactor lab manifest overview styling

---

packages/esm-providers-app/src/provider-alert-message/alert-message-banner.component.test.tsx
packages/esm-providers-app/src/provider-alert-message/alert-message-banner.component.tsx
packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.test.tsx
packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
packages/esm-providers-app/src/routes.json
packages/esm-providers-app/src/types/index.ts
packages/esm-providers-app/src/workspace/hook/provider-form.resource.ts
packages/esm-providers-app/translations/en.json
yarn.lock

Your Licence Number will be expiring on {Date} Once expired any services offered may not be claimed from SHA
https://github.com/user-attachments/assets/ba4103b7-209e-4612-a5fa-0895eef4b20f
*None.*
*None.*
*None.*

(feat) : add alert message to notify provider on reg license expired date

---

packages/esm-morgue-app/src/card/avail-compartment.compartment.tsx
packages/esm-morgue-app/src/left-panel/morgue-left-panel-link.component.tsx
packages/esm-morgue-app/src/panels/attachments.component.tsx
packages/esm-morgue-app/src/root.component.tsx

(fix): Correct URL segment extraction for UUID paths in morgue module

---

packages/esm-morgue-app/src/panels/attachments.component.tsx
packages/esm-morgue-app/translations/en.json

(feat): Added a file attachment functionality in the morgue module

---

packages/esm-morgue-app/src/panels/billing-history.component.tsx
packages/esm-morgue-app/translations/en.json

(feat): Added bill history and workspace feature to Morgue Module

---

package.json
packages/esm-billing-app/package-lock.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package-lock.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package-lock.json
packages/esm-pharmacy-app/package.json
packages/esm-providers-app/package-lock.json
packages/esm-providers-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package-lock.json
packages/esm-version-app/package.json

We have had a lot of bug fixes and ehancement, IMO it would be good to have a cut off for the many changes done so far.
cc @palladiumkenya/qa @ojwanganto @makombe @its-kios09 @Omoshlawi 
*None.*
*None.*
*None.*

(release) update to version v5.3.5

---

packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.test.tsx
packages/esm-billing-app/translations/en.json

This a simple change, aimed at trying to reduce number of re-renders for an item.
*None.*
*None.*
*None.*

(feat) : Enhance performance of test-order-action extension

---

packages/esm-billing-app/src/benefits-package/forms/benefits-eligibility-request-form.scss

Simple fix following a breaking change introduced here https://github.com/palladiumkenya/kenyaemr-esm-3.x/pull/413
*None.*
*None.*
*None.*

(fix) : fix css styling breaking global elements

---

packages/esm-billing-app/src/billing-form/hie.resource.tsx
packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.component.tsx
packages/esm-billing-app/src/config-schema.ts
packages/esm-billing-app/translations/en.json
yarn.lock

see:-  https://thepalladiumgroup.atlassian.net/browse/KHP3-6966
*None.*

(feat) KHP3-6966 : Rename SHA verify button and insurance scheme labels [SHIF]

---

packages/esm-care-panel-app/src/hooks/useHeiOutcome.ts
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx

…vices program
*None.*
*None.*
*None.*

(feat) : Disable 'Continue' button until HEI outcome is selected for MCH child services

---

package.json
packages/esm-billing-app/package-lock.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-providers-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

(release) update to version v5.3.6 cc @palladiumkenya/qa the current version deployed has issues on billing-services
*None.*
*None.*
*None.*

(release) update to version v5.3.6

---

.gitignore
packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx

This PR refines the mutation process in the care-panel by targeting specific endpoints, avoiding unnecessary mutations across all endpoints.
[Kapture 2024-11-05 at 19.13.24.webm](https://github.com/user-attachments/assets/ab1a8fb5-ff32-4e57-8bbc-645e8fedbccc)
*None.*
*None.*

(feat) : Add mutation for care-panel endpoints

---

packages/esm-morgue-app/README.md

*None.*
see: https://thepalladiumgroup.atlassian.net/browse/KHP3-7036
*None.*
*None.*

(feat) KPH3-7036 : Update README with morgue functionality

---

.github/workflows/ci.yml

Add cache in attempt to make our ci run faster
From 7 minutes
To 1 minute here
No UI changes
*None.*
*None.*

(ci) KHP3-7049 : Optimize release workflow by leveraging build artifacts

---

.github/workflows/ci.yml

Fix failing pre-release
*None.*
*None.*
*None.*

(ci) : fix pre-release failing

---

packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
packages/esm-care-panel-app/src/regimen-editor/utils.tsx

(fix) : Filter regimen lines using correct criteria

---

.github/workflows/ci.yml

(ci) : fix pre-release failing follow up

---

packages/esm-billing-app/src/config-schema.ts

This PR fixes a small object config issue to allow editing of the credentials. (temporarily).
*None.*
*None.*
*None.*

(fix): add object keys to PDSL configuration

---

packages/esm-billing-app/src/billable-services/payment-history/payment-history-viewer.component.tsx
packages/esm-billing-app/src/bills-table/bills-table.component.tsx

* Add Status in the payment history table
* Add Status in the Overview patient bill summary
*None.*
*None.*
*None.*

(feat) : Add payment status column on bill overview and payment history tables

---

packages/esm-billing-app/src/billable-services/payment-history/payment-history-table.component.tsx
packages/esm-billing-app/src/billable-services/payment-history/payment-history-viewer.component.tsx
packages/esm-billing-app/translations/en.json

* Add translation support to the table header labels
*None.*
*None.*
*None.*

(fix): Translate header label

---

packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
packages/esm-billing-app/src/billing-form/check-in-form.utils.tsx
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
packages/esm-billing-app/src/config-schema.ts

https://github.com/user-attachments/assets/3840ccd9-a17f-4caf-a4d4-882d12620e6e
https://thepalladiumgroup.atlassian.net/browse/KHP3-7080
*None.*

(fix) KHP3-7080 : fix checkin visit attributes not saving 

---

packages/esm-lab-manifest-app/src/lab-manifest.resources.ts

https://github.com/user-attachments/assets/d6ede781-c383-4eb0-b62a-a620941ed423
https://thepalladiumgroup.atlassian.net/browse/KHP3-7078
*None.*

KPH3-7078-Added printing ability for ready to send manifest

---

packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/print-bill-receipt/print-bill-receipt.resource.ts
packages/esm-billing-app/src/invoice/print-bill-receipt/print-bill-receipt.scss
packages/esm-billing-app/src/invoice/print-bill-receipt/print-receipt-action.component.tsx
packages/esm-billing-app/src/invoice/print-bill-receipt/receipt-print-preview.modal.tsx
packages/esm-billing-app/src/routes.json

https://github.com/user-attachments/assets/43be67fb-d291-4964-8459-d9e9b5877aa2
https://thepalladiumgroup.atlassian.net/browse/KHP3-7086
*None.*

(feat)KHP3-7086-Add Paid bill receipt print preview

---

packages/esm-providers-app/src/config-schema.ts

(feat) aligned other identifier types

---

packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx

Fix date format effecting loading patient summary

---

packages/esm-billing-app/src/metrics-cards/metrics.resource.ts

Fix cumulative and pending bills showing NaN

---

packages/esm-billing-app/src/billable-services/bill-manager/workspaces/cancel-bill/cancel-bill.workspace.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill/useEditBillFormSchema.tsx
packages/esm-billing-app/src/billing.resource.ts
packages/esm-billing-app/src/bills-table/bills-table.component.tsx
packages/esm-billing-app/src/claims/dashboard/table/claims-table.component.tsx
packages/esm-billing-app/src/claims/pre-auth/table/pre-auth-table.component.tsx
packages/esm-billing-app/src/invoice/invoice-table.component.tsx
packages/esm-billing-app/src/utils.ts

Additional null checks for billing

---

packages/esm-billing-app/src/metrics-cards/metrics-cards.component.tsx
packages/esm-billing-app/src/metrics-cards/metrics-cards.scss
packages/esm-billing-app/src/metrics-cards/metrics.resource.ts

This PR fixes the terminology on the billing overview page to accurately reflect the billing information provided. Also I tweaked the spacing to make the page look more consistent.
*None.*
*None.*
*None.*

(style) : rename cumulative bills to today's bills

---

e2e/specs/billing/billling-history.spec.ts
packages/esm-billing-app/src/metrics-cards/metrics-cards.test.tsx

This PR fixes the broken unit tests on #491.
*None.*
*None.*
*None.*

fix (tests) : broken billing overview tests

---

packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/cancel-line-item.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/delete-bill-action-button.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/edit-line-item.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/refund-line-item.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/bill-actions/waive-bill-action-button.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/bill-line-items.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/bill-manager.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/patient-bills.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill/waive-bill-form.workspace.tsx
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json

This is the first step to have the roles and privilege to work correctly with extension system to enable control access. A follow up PR to follow up on the config repo
No UI changes
*None.*
*None.*

(feat) KHP3-7125 : Add role and privilege to control access to bill manager function

---

e2e/specs/billing/billling-history.spec.ts
packages/esm-billing-app/src/billing.resource.ts
packages/esm-billing-app/src/metrics-cards/metrics-cards.component.tsx
packages/esm-billing-app/src/metrics-cards/metrics-cards.test.tsx
packages/esm-billing-app/src/metrics-cards/metrics.resource.ts
packages/esm-billing-app/src/types/index.ts

This PR adds an exempted tile to the billing overview page.
*None.*
cc @ojwanganto

(feat) : exempted bills on billing homepage

---

.github/workflows/ci.yml

Ensure wok flows run on every merge
*None.*
*None.*
*None.*

(chore) : run workflows on every merge to main branch

---

packages/esm-admin-app/src/components/logs-table/operation-log-table.component.tsx
packages/esm-admin-app/src/config-schema.ts

(refactor) follow up changes on the esm admin app

---

packages/esm-billing-app/src/billable-services/billiable-item/test-order/dispense.resource.tsx
packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.test.tsx
packages/esm-version-app/src/release-version.js

This is a refactor for bill-actions on orders to prevent actioning on orders with pending bills
- Update to use workspace to launch dispensing workspace
*None.*
*None.*
*None.*

(refactor) : Update dispensing to prevent processing of drugs with unsetted bill

---

package.json
packages/esm-admin-app/package.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-providers-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

- Release v5.3.9
*None.*
*None.*
*None.*

(release) : v5.3.9

---

packages/esm-billing-app/src/hooks/use-payments-reconciler.tsx

Fix bill payment page failing by adding a null check for usePaymentsReconciler hook
*None.*
*None.*
*None.*

(fix) : error on `usePaymentsReconciler`

---

packages/esm-cross-border-app/package.json
packages/esm-cross-border-app/translations/en.json

(chore) : minor fix and add cross border translation

---

packages/esm-cross-border-app/src/components/encounters/encounter.component.tsx

Remove forms link from table

---

packages/esm-providers-app/src/provider-alert-message/alert-message-banner.component.test.tsx

Fix failing unit test
*None.*
*None.*
*None.*

(test) : fix failing unit test due to mocked time failing

---

packages/esm-cross-border-app/src/components/encounters/encounter.component.tsx
packages/esm-cross-border-app/src/components/encounters/encounter.scss

(feat) : Add paginate cross border encounters

---

yarn.lock

bump `@openmrs/esm-patient-common-lib` version
*None.*
*None.*
*None.*

(chore) : bump `@openmrs/esm-patient-common-lib` version

---

packages/esm-admin-app/src/components/dashboard/dashboard.component.tsx
packages/esm-admin-app/src/components/logs-table/operation-log-resource.ts
packages/esm-admin-app/src/components/logs-table/operation-log-table.component.tsx
packages/esm-admin-app/translations/en.json

 (feat): KHP3 -Add custom endpoint for recreateFacilitywideTables functionality

---

package.json
packages/esm-admin-app/package.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-cross-border-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-providers-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

Update to version 5.4.0 cc @ojwanganto @palladiumkenya/qa 
*None.*
*None.*
*None.*

(release) : v5.4.0

---

packages/esm-shr-app/src/referrals/dependents/dependents.component.tsx

(fix) : relationship list fix

---

packages/esm-billing-app/src/benefits-package/forms/package-interventions.component.tsx
packages/esm-billing-app/src/billable-services/bill-manager/modals/refund-bill.modal.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/edit-bill/edit-bill-form.workspace.tsx
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/waive-bill/waive-bill-form.workspace.tsx
packages/esm-billing-app/src/billable-services/billable-exemptions/billable-exemptions-viewer.component.tsx
packages/esm-billing-app/src/billable-services/billables/commodity/commodity-form.workspace.tsx
packages/esm-billing-app/src/billable-services/billables/services/service-form.workspace.tsx
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
packages/esm-billing-app/src/claims/claims-management/main/claims-pre-auth-main.component.tsx
packages/esm-billing-app/src/claims/claims-management/table/claims-list-table.component.tsx
packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/payments/payment-form/payment-form.component.tsx
packages/esm-billing-app/translations/en.json

fix ESM billing app linting warnings
*None.*
*None.*
*None.*

chore: fix ESM billing app linting warnings

---

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx
packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
packages/esm-care-panel-app/src/care-programs/care-programs.test.tsx
packages/esm-patient-clinical-view-app/src/clinical-view-group/clinical-view-group.resource.ts
packages/esm-patient-clinical-view-app/src/clinical-view-group/createDashboardGroup.tsx
packages/esm-patient-clinical-view-app/src/peer-calendar/forms/form-entry.workspace.tsx
packages/esm-patient-clinical-view-app/src/peer-calendar/table/peer-completion-status.component.tsx
packages/esm-patient-clinical-view-app/src/relationships/forms/relationships-update-form.workspace.tsx
packages/esm-patient-clinical-view-app/src/ui/encounter-list/encounter-list.component.tsx
packages/esm-providers-app/src/provider-alert-message/alert-message-banner.component.tsx
packages/esm-shr-app/src/referrals/referrals-actions.component.tsx
packages/esm-version-app/src/hooks/useFrontendModules.tsx

chore : fix lint warning on version, shr, version and provider apps

---

packages/esm-admin-app/src/components/facility-setup/facility-info.component.tsx

https://thepalladiumgroup.atlassian.net/browse/KHP3-7452
*None.*
*None.*

fix: validate SHA facility expiry date before formatting

---

packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx

Fix linting errors
*None.*
*None.*
*None.*

(chore) : squash linting errors on care-panels

---

packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx

Show exact report date when printing summary rather than Today

---

packages/esm-facility-dashboard-app/src/surveillance/summary-cards/surveillance-summary-cards.component.tsx
packages/esm-facility-dashboard-app/src/types/index.ts

update surveillance summary cards to use clinical action thresholds and denominators to show arrow indication

---

packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx

Display CD4 Count Date from Backend in Pre-Formatted Format

---

packages/esm-care-panel-app/src/iit-risk-score/iit-risk-score.component.tsx

(fix) IIT riskscore evaluation date preventing loading of care panel

---

packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx

Show Out of stock button for drugs only

---

packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.component.tsx

(fix): Displaying out of stock button

---

packages/esm-billing-app/src/invoice/invoice.component.tsx

*None.*
*None.*
https://thepalladiumgroup.atlassian.net/browse/KHP3-7648
*None.*

(fix) KHP3-7648: Bug on claim process button available for other types of payment than Insurance

---

packages/esm-admin-app/src/components/users/manage-users/user-management.workspace.tsx
packages/esm-admin-app/src/components/users/userManagementFormSchema.tsx
packages/esm-admin-app/src/constants.ts

* Validate existing username
*None.*
*None.*
*None.*

(fix) Validate existing username

---

packages/esm-billing-app/src/benefits-package/benefits-package.resources.tsx
packages/esm-billing-app/src/benefits-package/forms/benefit-pre-auth-form.workspace.tsx
packages/esm-billing-app/src/benefits-package/forms/interventions-form.component.tsx
packages/esm-billing-app/src/benefits-package/forms/packages-and-interventions-form.component.tsx
packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
packages/esm-billing-app/src/billing-form/check-in-form.utils.tsx
packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
packages/esm-billing-app/src/claims/dashboard/form/claims-form.resource.ts
packages/esm-billing-app/src/config-schema.ts
packages/esm-billing-app/src/constants.ts
packages/esm-billing-app/src/hooks/useInterventions.ts
packages/esm-billing-app/src/types/index.ts

… on visit attribute for consumption at claims form
https://github.com/user-attachments/assets/9f4a00da-a8a6-43ea-b65d-c79ee974ad97
https://thepalladiumgroup.atlassian.net/browse/KHP3-7649
https://thepalladiumgroup.atlassian.net/browse/KHP3-7652
https://thepalladiumgroup.atlassian.net/browse/KHP3-7650
*None.*

Add packages and intervention at checking and persisting in visit attribute

---

packages/esm-billing-app/src/billable-services/bill-manager/workspaces/create-bill/create-bill.style.scss
packages/esm-billing-app/src/billable-services/bill-manager/workspaces/create-bill/create-bill.workspace.tsx
packages/esm-billing-app/src/billable-services/billiable-item/order-actions/components/generic-button.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/order-actions/components/lab-order-button.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/order-actions/components/medication-order-button.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/order-actions/components/order-action-button.component.tsx
packages/esm-billing-app/src/billable-services/billiable-item/order-actions/hooks/useLabOrderAction.ts
packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json

https://thepalladiumgroup.atlassian.net/browse/KHP3-7570
[Kapture 2025-03-27 at 22.55.37.webm](https://github.com/user-attachments/assets/5f7fa3a4-b9ef-4905-934d-5b5bc113651c)
*None.*
*None.*

feat KHP3-7570 : Initiate billing of tests from the laboratory to ensure efficient patient flow

---

packages/esm-admin-app/src/components/facility-setup/facility-info.component.tsx

* Update facility registry code
*None.*
*None.*
*None.*

(fix): Update Facility registry code

---

packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.component.tsx
packages/esm-billing-app/src/billing-form/social-health-authority/sha-number-validity.scss

* Add CR number check (PHC)
* Add status - 1 (PHC, SHIF, ECCIF)
* 
*None.*
*None.*
*None.*

(feat) Add member CR number check

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/hooks/usePartograph.ts
packages/esm-patient-clinical-view-app/src/index.ts
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/labour-delivery.component.tsx
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/partography/partograph-chart.scss
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/partography/partograph-chart.tsx
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/partography/partograph.component.tsx
packages/esm-patient-clinical-view-app/src/routes.json
packages/esm-patient-clinical-view-app/src/utils/constants.ts

See https://thepalladiumgroup.atlassian.net/browse/KHP3-7787
[Kapture 2025-04-15 at 14.03.22.webm](https://github.com/user-attachments/assets/824a1185-bfa1-446c-aac3-5d341532fcba)
*None.*
*None.*

(fix): KHP3-7787 - Fixed missing partograph rendering and improved chart layout for better visibility

---

packages/esm-admin-app/src/components/modal/hwr-confirmation.modal.tsx
packages/esm-admin-app/src/components/modal/hwr-sync.modal.tsx
packages/esm-admin-app/src/components/users/manage-users/user-details/user-details.component.tsx
packages/esm-admin-app/src/components/users/manage-users/user-list/user-list.component.tsx
packages/esm-admin-app/src/components/users/manage-users/user-management.workspace.tsx
packages/esm-admin-app/src/components/users/userManagementFormSchema.tsx
packages/esm-admin-app/src/config-schema.ts
packages/esm-admin-app/translations/en.json

https://thepalladiumgroup.atlassian.net/browse/KHP3-7829
*None.*

(feat) KHP3-7829: Added the provider unique identifier attribute

---

packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
packages/esm-billing-app/src/hooks/useProviderList.ts
packages/esm-billing-app/src/invoice/payments/payment-status-ckecker.modal.tsx
packages/esm-lab-manifest-app/src/tables/lab-manifest-table.component.tsx
packages/esm-patient-clinical-view-app/src/maternal-and-child-health/partography/partograph-chart.tsx

* Add provider list for selection during claim submission.
[Screencast from 24-04-2025 01:38:54 ALASIRI.webm](https://github.com/user-attachments/assets/90b4d177-1269-4169-a672-c1b0f7505923)
*None.*
*None.*
*None.*

(fix): Fix provider list

---

packages/esm-billing-app/src/hooks/useInterventions.ts
packages/esm-billing-app/src/hooks/usePackages.ts

https://github.com/user-attachments/assets/ea449515-af33-4289-a2ef-4e910f9237e4
*None.*
*None.*

Adapt Packages and interventions component to endpoint updates

---

package.json
packages/esm-admin-app/package.json
packages/esm-billing-app/package.json
packages/esm-billing-app/src/billable-services/bill-manager/modals/delete-billable-service.modal.tsx
packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
packages/esm-billing-app/src/billable-services/billables/charge-summary-table.component.test.tsx
packages/esm-billing-app/src/billable-services/billables/charge-summary-table.component.tsx
packages/esm-billing-app/src/billable-services/billables/charge-summary.resource.tsx
packages/esm-billing-app/src/billable-services/billables/commodity/commodity-form.workspace.test.tsx
packages/esm-billing-app/src/billable-services/billables/commodity/commodity-form.workspace.tsx
packages/esm-billing-app/src/billable-services/billables/commodity/stock-search.component.tsx
packages/esm-billing-app/src/billable-services/billables/form-helper.ts
packages/esm-billing-app/src/billable-services/billables/form-schemas.tsx
packages/esm-billing-app/src/billable-services/billables/services/concept-search.component.tsx
packages/esm-billing-app/src/billable-services/billables/services/price.component.tsx
packages/esm-billing-app/src/billable-services/billables/services/service-form.workspace.test.tsx
packages/esm-billing-app/src/billable-services/billables/services/service-form.workspace.tsx
packages/esm-billing-app/translations/en.json
packages/esm-care-panel-app/package.json
packages/esm-cross-border-app/package.json
packages/esm-facility-dashboard-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-shr-app/package.json
yarn.lock

This PR addresses a number of issues
1. Resolve error when trying to setup the package by running `openmrs develop ...arg`
2. Ensure we use one endpoint for `BillableServices`
3. Prevent duplication of billable services 
4. Add unit test to prevent regression
Changes made here are related to https://github.com/palladiumkenya/openmrs-module-kenyaEMRCashier/pull/69
[Kapture 2025-04-30 at 12.22.19.webm](https://github.com/user-attachments/assets/c912914e-12e1-44b0-8cd4-03264d85271b)
*None.*
*None.*

(feat) : Update billable service endpoint, improve test coverage

---

packages/esm-billing-app/src/claims/claims-management/header/filter-header.component.tsx
packages/esm-billing-app/src/claims/claims-management/table/claim-table.component.tsx
packages/esm-billing-app/src/claims/claims-management/table/manage-claim-request.modal.tsx
packages/esm-billing-app/src/claims/utils.ts
packages/esm-billing-app/src/types/index.ts

* The user gets all the response UUIDs to be updated and updates all claim statuses at once in sequence.
[Screencast from 09-05-2025 11:00:27 ASUBUHI.webm](https://github.com/user-attachments/assets/4eb4fdad-5bf8-4636-8bbb-e5f8c50e33aa)
*None.*
*None.*
*None.*

(feat): update all claim statuses

---

package.json
packages/esm-admin-app/package.json
packages/esm-billing-app/package.json
packages/esm-billing-app/translations/en.json
packages/esm-care-panel-app/package.json
packages/esm-cross-border-app/package.json
packages/esm-facility-dashboard-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-patient-clinical-view-app/package.json
packages/esm-patient-flags-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-shr-app/package.json
packages/esm-version-app/package.json

(chore) : release v5.4.1

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/in-patient/in-patient.component.tsx

(feat) Add logic to hide partograph for all male and only female under 10 years

---

packages/esm-patient-clinical-view-app/src/config-schema.ts
packages/esm-patient-clinical-view-app/src/in-patient/in-patient.component.tsx

(feat) Add logic to evaluate in months and days

---

packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json

(fix) restore billing module nav-group link

---

packages/esm-version-app/src/routes.json

(feat) Add billing dashboard navigation group config

---

packages/esm-billing-app/src/invoice/invoice.component.tsx

(fix) Fix treatment end date on the claims form not populating

---

packages/esm-billing-app/src/index.ts
packages/esm-billing-app/src/routes.json
packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
packages/esm-version-app/src/routes.json

- Resloved duplicate billing nav links
- Clean up old nav links
https://github.com/user-attachments/assets/b19e8ee1-06dc-45b2-aefc-6c8b35a84f24
*None.*
*None.*
*None.*

(refactor) Resolve billing nav link duplication, also cleaned up unsued duplications for claims as well

---

packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/src/invoice/invoice.resource.ts
packages/esm-billing-app/src/types/index.ts
packages/esm-billing-app/translations/en.json

**Without registration number setup**
**With  registration number already setup**
*None.*
*None.*

(feat): Validate facility registration number before claim processing

---

packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
packages/esm-patient-flags-app/src/navbar/navbar-action-button.test.tsx

(chore): remove legacy admin menu item

---

packages/esm-patient-flags-app/src/navbar/nav-utils.tsx

Rename KenyaEMR homepage privilage

---

packages/esm-billing-app/src/invoice/invoice.component.tsx
packages/esm-billing-app/translations/en.json

(fix) fix mutation on claims form

---

packages/esm-care-panel-app/src/index.ts
packages/esm-care-panel-app/src/patient-discharge/discharge-workspace-siderail.component.tsx
packages/esm-care-panel-app/src/patient-discharge/patient-discharge.resource.tsx
packages/esm-care-panel-app/src/patient-discharge/patient-discharge.workspace.test.tsx
packages/esm-care-panel-app/src/patient-discharge/patient-discharge.workspace.tsx
packages/esm-care-panel-app/src/routes.json
packages/esm-care-panel-app/src/types/index.ts

See https://thepalladiumgroup.atlassian.net/browse/KHP3-8114
[Kapture 2025-06-12 at 15.16.54.webm](https://github.com/user-attachments/assets/ea2703e9-78a5-41d5-a305-81eb98be8da7)
*None.*
*None.*

feat KHP3-8114 : open discharge form instead of auto-discharging inpatients

---

packages/esm-care-panel-app/src/program-summary/program-summary.component.tsx

(fix)KHP3-7931: TB regimen start date defaults to ART regimen start date

---

packages/esm-billing-app/src/invoice/payments/utils.ts

Resolved the issue above
*None.*
*None.*
*None.*

fix : resolve regression on payment method instance type

---

packages/esm-billing-app/src/invoice/payments/payments.test.tsx
packages/esm-billing-app/src/invoice/payments/utils.ts

This PR ensures that payment methods requiring additional attributes are captured correctly. e.g **mobile money** requires additional reference information for completeness
*None.*
*None.*
*None.*

fix : resolve error while processing mobile money payment method

---

packages/esm-lab-manifest-app/src/forms/sample-delete-confirm-dialog.modal.tsx
packages/esm-lab-manifest-app/src/header/lab-manifest-detail-header.component.tsx
packages/esm-lab-manifest-app/src/header/lab-manifest-header.scss
packages/esm-lab-manifest-app/src/header/lab-manifest-table-filters-header.component.tsx
packages/esm-lab-manifest-app/src/hooks/useLabManifest.tsx
packages/esm-lab-manifest-app/src/hooks/useLabManifestOrders.ts
packages/esm-lab-manifest-app/src/tables/lab-manifest-samples.component.tsx
packages/esm-lab-manifest-app/src/tables/lab-manifest-table.component.tsx
packages/esm-lab-manifest-app/src/tables/patient-name-cell.component.tsx
packages/esm-lab-manifest-app/translations/en.json

- Add search functionality to manifest samples
- Add requeue to the manifest detail page
https://github.com/user-attachments/assets/16c33e6c-685b-4eff-9ee1-a99efdcee50a
https://thepalladiumgroup.atlassian.net/browse/KHP3-8045
*None.*

KHP3-8045: Avail a search field under any manifests created to enable searching of patients

---

packages/esm-adr-app/jest.config.js
packages/esm-adr-app/package.json
packages/esm-adr-app/src/components/dashboard/dashboard-view.component.tsx
packages/esm-adr-app/src/components/dashboard/dashboard-view.scss
packages/esm-adr-app/src/components/dashboard/home-dashboard.component.tsx
packages/esm-adr-app/src/components/dashboard/home-dashboard.scss
packages/esm-adr-app/src/components/encounters/adr-encounter.component.tsx
packages/esm-adr-app/src/components/encounters/encounter.resource.tsx
packages/esm-adr-app/src/components/encounters/encounter.scss
packages/esm-adr-app/src/components/header/header.component.tsx
packages/esm-adr-app/src/components/patient-adr.workspace.tsx
packages/esm-adr-app/src/components/side-menu/side-menu.component.tsx
packages/esm-adr-app/src/components/summary/summary.component.tsx
packages/esm-adr-app/src/components/summary/summary.scss
packages/esm-adr-app/src/config-schema.ts
packages/esm-adr-app/src/declarations.d.ts
packages/esm-adr-app/src/index.ts
packages/esm-adr-app/src/root.component.tsx
packages/esm-adr-app/src/routes.json
packages/esm-adr-app/src/types/index.ts
packages/esm-adr-app/translations/en.json
packages/esm-adr-app/tsconfig.json
packages/esm-adr-app/webpack.config.js
packages/esm-patient-flags-app/src/navbar/nav-utils.tsx
yarn.lock

Adr work space

---

packages/esm-morgue-app/src/routes.json

(fix) fixed the double left panel for mortuary

---

package.json
packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
packages/esm-billing-app/src/helpers/functions.ts

(feat) Add time to the claims form treatment start and end

---

packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
packages/esm-billing-app/src/claims/utils.ts

fix: Convert formatted dates to ISO format and Localstring on UI in claims submission

---

package.json
packages/esm-admin-app/package.json
packages/esm-adr-app/package.json
packages/esm-billing-app/package.json
packages/esm-care-panel-app/package.json
packages/esm-care-panel-app/src/patient-summary/patient-summary.component.test.tsx
packages/esm-care-panel-app/src/patient-summary/patient-summary.component.tsx
packages/esm-cross-border-app/package.json
packages/esm-facility-dashboard-app/package.json
packages/esm-lab-manifest-app/package.json
packages/esm-morgue-app/package.json
packages/esm-pharmacy-app/package.json
packages/esm-shr-app/package.json
packages/esm-shr-app/src/shrpatient-summary/shrpatient-summary.component.tsx
packages/esm-shr-app/translations/am.json
packages/esm-shr-app/translations/en.json
packages/esm-shr-app/translations/sw.json
yarn.lock

Downgrade react-to-print for compatibility with community instance
This PR downgrades the react-to-print dependency to match the version currently deployed on the community instance, resolving compatibility issues that were preventing drug prescription printing functionality.
*None.*
*None.*
*None.*

fix : resolve printing issues that affect dispensing app

---

packages/esm-patient-clinical-view-app/src/index.ts
packages/esm-patient-clinical-view-app/src/left-panel-link.component.tsx
packages/esm-patient-clinical-view-app/src/routes.json

- Fix case management and peer calendar links bug
- Tested all links to ascertain they all are working fine
[Screencast from 2025-08-14 11-42-14.webm](https://github.com/user-attachments/assets/3cc64fb1-407b-44c1-8347-edf92b51cb2f)
*None.*
*None.*
*None.*

fix peer calendar and case management links

---

packages/esm-billing-app/src/routes.json
packages/esm-express-workflow-app/src/components/accounting/accounting.component.tsx

Fix extension slot name

---

packages/esm-express-workflow-app/src/root.scss

(chore) Remove fixed height calculation to prevent unwanted scrollbar

---

packages/esm-express-workflow-app/src/components/pharmacy/pharmacy.component.tsx

added a slot to inject dispensing app for pharmacy
*None.*
*None.*
*None.*

added slot for pharmacy app

---

packages/esm-adr-app/src/components/adr-patient-summary/patient-summary.component.tsx
packages/esm-adr-app/src/components/adr-patient-summary/patient-summary.scss
packages/esm-adr-app/src/components/dashboard/dashboard-view.component.tsx
packages/esm-adr-app/src/components/dashboard/home-dashboard.component.tsx
packages/esm-adr-app/src/components/encounters/adr-encounter.component.tsx
packages/esm-adr-app/src/components/encounters/encounter.resource.tsx
packages/esm-adr-app/src/components/encounters/encounter.scss
packages/esm-adr-app/src/components/encounters/patient-encounter.component.tsx
packages/esm-adr-app/src/components/patient-search/patient-search.component.tsx
packages/esm-adr-app/src/components/patient-search/patient-search.scss
packages/esm-adr-app/src/components/patient-search/useInitialize.ts
packages/esm-adr-app/src/components/summary/summary.component.tsx
packages/esm-adr-app/src/components/summary/summary.scss
packages/esm-adr-app/src/config-schema.ts
packages/esm-adr-app/src/root.component.tsx
packages/esm-adr-app/translations/am.json
packages/esm-adr-app/translations/en.json
packages/esm-adr-app/translations/sw.json

Add ability to launch forms from adr package
*None.*
*None.*

(feat) : Add ability to launch forms from ADR

---

packages/esm-version-app/src/index.ts
packages/esm-version-app/src/routes.json
packages/esm-version-app/translations/am.json
packages/esm-version-app/translations/en.json
packages/esm-version-app/translations/sw.json

Add Kenyaemr imaging and radiology link override without icon for consistency

---

packages/esm-admin-app/src/components/provider-banner/provider-banner.component.tsx

(fix): Fix translation issues on the HIE provider banner

---

packages/esm-express-workflow-app/src/routes.json
packages/esm-express-workflow-app/src/shared/patient-chart/patient-chart.component.tsx

fix: Add slot -> extension route mapping for mch program management and fix workspace container context

---

packages/esm-billing-app/src/claims/dashboard/form/claims-form.component.tsx
packages/esm-billing-app/src/config-schema.ts
packages/esm-billing-app/src/hooks/useOTP.ts
packages/esm-billing-app/src/hooks/usePhoneNumber.ts
packages/esm-billing-app/src/invoice/invoice-actions.component.tsx
packages/esm-billing-app/src/types/index.ts

(feat) Add OTP verification onsubmit claim

---

packages/esm-billing-app/src/billing-dashboard/billing-dashboard.component.tsx
packages/esm-billing-app/src/bills-table/bills-table.component.tsx
packages/esm-billing-app/src/invoice/invoice-actions.component.tsx
packages/esm-billing-app/src/left-panel-link.component.tsx
packages/esm-billing-app/src/root.component.tsx

(fix): Fixed the billing routing architecture and keep navigation links active on sub-routes

---

packages/esm-express-workflow-app/src/components/consultation/consultation.component.tsx

(chore) Removed unwanted extra pageheader and illustration on consultation app

---

packages/esm-express-workflow-app/src/components/mch/programs/program.workspace.tsx
packages/esm-express-workflow-app/src/shared/patient-chart/patient-chart.component.tsx
packages/esm-express-workflow-app/src/shared/patient-chart/patient-chart.resources.ts

Fix duplicate launching program enrollment workspace

---

packages/esm-express-workflow-app/src/components/mch/mch.scss
packages/esm-express-workflow-app/src/components/pharmacy/pharmacy.component.tsx
packages/esm-express-workflow-app/src/routes.json
packages/esm-morgue-app/src/dashboard.meta.ts
packages/esm-morgue-app/src/index.ts
packages/esm-morgue-app/src/routes.json

Add mortuary link to DHA workflow

---

packages/esm-billing-app/src/billing-tabs/billling-tabs.component.tsx

Add claims and preAuth to DHA workflow

---

packages/esm-patient-flags-app/src/navbar/nav-utils.component.tsx

Add service queues configuration to app menu

---

packages/esm-care-panel-app/src/care-programs/care-program.resource.ts

- Wired forms for MAT, HIV, KVP, NCD,PREP, TPT,Violence screening and TB
*None.*
*None.*
*None.*

Wire forms for MAT, HIV, KVP, NCD,PREP, TPT,Violence screening and TB
